-- Backfill billing_subscriptions for any project that doesn't yet have an
-- active row. Idempotent — uses the partial unique index
-- billing_subscriptions_project_active_uq to short-circuit duplicates.
-- The id column has no DB-level default (cuid2 is generated by the ORM),
-- so we use gen_random_uuid()::text as a portable substitute here.

INSERT INTO billing_subscriptions (
    id,
    project_id,
    state,
    tier,
    cycle
)
SELECT
    gen_random_uuid()::text,
    p.id,
    'free',
    'free',
    'monthly'
FROM projects p
WHERE NOT EXISTS (
    SELECT 1
    FROM billing_subscriptions bs
    WHERE bs.project_id = p.id AND bs.state != 'deleted'
);
