import type { Product } from "./types";

export const PRODUCTS_CATALOG: ReadonlyArray<Product> = [
  {
    id: "prod_01HX2KA1M8",
    sku: "premium_yearly",
    name: "Premium Annual",
    group: "Premium",
    entitlements: ["premium", "unlimited_exports"],
    duration: "P1Y",
    price: 79.99,
    currency: "USD",
    trial: "7d",
    subs: 612,
    mrr: 5080,
    status: "active",
    stores: ["ios", "android"],
    created: "2025-08-14",
    updated: "2m ago",
  },
  {
    id: "prod_01HX2K9Z3F",
    sku: "premium_monthly",
    name: "Premium Monthly",
    group: "Premium",
    entitlements: ["premium", "unlimited_exports"],
    duration: "P1M",
    price: 9.99,
    currency: "USD",
    trial: "7d",
    subs: 981,
    mrr: 9799,
    status: "active",
    stores: ["ios", "android"],
    created: "2025-08-14",
    updated: "12s ago",
  },
  {
    id: "prod_01HX2KB4P2",
    sku: "pro_monthly",
    name: "Pro Monthly",
    group: "Pro",
    entitlements: ["pro"],
    duration: "P1M",
    price: 4.99,
    currency: "USD",
    trial: null,
    subs: 428,
    mrr: 2137,
    status: "active",
    stores: ["ios", "android"],
    created: "2025-09-02",
    updated: "1h ago",
  },
  {
    id: "prod_01HX2KC7Q9",
    sku: "pro_yearly",
    name: "Pro Annual",
    group: "Pro",
    entitlements: ["pro"],
    duration: "P1Y",
    price: 39.99,
    currency: "USD",
    trial: null,
    subs: 62,
    mrr: 206,
    status: "active",
    stores: ["ios", "android"],
    created: "2025-09-02",
    updated: "4h ago",
  },
  {
    id: "prod_01HX2KD2R1",
    sku: "lifetime_unlock",
    name: "Lifetime",
    group: "Premium",
    entitlements: ["premium", "lifetime_badge"],
    duration: "lifetime",
    price: 149.0,
    currency: "USD",
    trial: null,
    subs: 18,
    mrr: 0,
    status: "active",
    stores: ["ios", "android", "web"],
    created: "2025-10-11",
    updated: "2d ago",
  },
  {
    id: "prod_01HX2KE8S7",
    sku: "premium_weekly",
    name: "Premium Weekly",
    group: "Premium",
    entitlements: ["premium"],
    duration: "P1W",
    price: 2.99,
    currency: "USD",
    trial: "3d",
    subs: 142,
    mrr: 1702,
    status: "active",
    stores: ["ios", "android"],
    created: "2026-01-20",
    updated: "28m ago",
  },
  {
    id: "prod_01HX2KF3T4",
    sku: "starter_monthly",
    name: "Starter Monthly",
    group: "Starter",
    entitlements: ["basic"],
    duration: "P1M",
    price: 1.99,
    currency: "USD",
    trial: null,
    subs: 304,
    mrr: 605,
    status: "active",
    stores: ["android"],
    created: "2026-02-08",
    updated: "1d ago",
  },
  {
    id: "prod_01HX2KG9U6",
    sku: "premium_eu_yearly",
    name: "Premium Annual EU",
    group: "Premium",
    entitlements: ["premium", "unlimited_exports"],
    duration: "P1Y",
    price: 74.99,
    currency: "EUR",
    trial: "7d",
    subs: 188,
    mrr: 1172,
    status: "active",
    stores: ["ios", "android"],
    created: "2026-01-04",
    updated: "6h ago",
  },
  {
    id: "prod_01HX2KH5V2",
    sku: "credits_100",
    name: "100 Credits",
    group: "Credits",
    entitlements: [],
    duration: "consumable",
    price: 4.99,
    currency: "USD",
    trial: null,
    subs: null,
    mrr: 0,
    status: "active",
    stores: ["ios", "android"],
    created: "2026-03-15",
    updated: "3h ago",
  },
  {
    id: "prod_01HX2KJ1W0",
    sku: "credits_500",
    name: "500 Credits",
    group: "Credits",
    entitlements: [],
    duration: "consumable",
    price: 19.99,
    currency: "USD",
    trial: null,
    subs: null,
    mrr: 0,
    status: "active",
    stores: ["ios", "android"],
    created: "2026-03-15",
    updated: "3h ago",
  },
  {
    id: "prod_01HX2KK6X3",
    sku: "team_seat_monthly",
    name: "Team Seat",
    group: "Team",
    entitlements: ["pro", "team_features"],
    duration: "P1M",
    price: 8.99,
    currency: "USD",
    trial: "14d",
    subs: 54,
    mrr: 485,
    status: "draft",
    stores: ["web"],
    created: "2026-04-01",
    updated: "1h ago",
  },
  {
    id: "prod_01HX2KL2Y8",
    sku: "legacy_pro_annual",
    name: "Pro Annual (legacy)",
    group: "Pro",
    entitlements: ["pro"],
    duration: "P1Y",
    price: 29.99,
    currency: "USD",
    trial: null,
    subs: 208,
    mrr: 520,
    status: "archived",
    stores: ["ios", "android"],
    created: "2024-11-02",
    updated: "3mo ago",
  },
];

export const PRODUCT_GROUPS: ReadonlyArray<string> = [
  "All",
  "Premium",
  "Pro",
  "Starter",
  "Team",
  "Credits",
];
