#!/usr/bin/env bash
set -euo pipefail

# generate-swift-dist.sh — renders the standalone SwiftPM distribution package.
#
# External SPM consumers cannot depend on this monorepo: a tag here would carry
# a manifest whose binaryTarget points at a local path. They depend on a
# separate repository whose tags carry a manifest with a fixed url + checksum.
# That repository is generated output, never hand-edited.
#
# Usage: ./generate-swift-dist.sh <XCFRAMEWORK_ZIP_CHECKSUM> [OUT_DIR]

if [ $# -lt 1 ]; then
  echo "usage: $0 <XCFRAMEWORK_ZIP_CHECKSUM> [OUT_DIR]" >&2
  exit 2
fi

CHECKSUM="$1"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SWIFT_DIR="$(cd "$HERE/.." && pwd)"
CONFIG="$SWIFT_DIR/release.config.json"
OUT_DIR="${2:-$SWIFT_DIR/build/swift-dist}"

cfg() { ruby -rjson -e "print JSON.parse(File.read('$CONFIG'))['$1']"; }

REPO_SLUG="$(cfg repoSlug)"
VERSION="$(cfg version)"
POD_NAME="$(cfg podName)"
XCF_NAME="$(cfg xcframeworkName)"

# The release asset's filename is DERIVED, never written out: release-pod.sh
# names the zip `${xcframeworkName%.xcframework}-$VERSION.xcframework.zip` and
# release-sdk.yml uploads it under that name. Spelling it literally here is how
# a rename of `xcframeworkName` produces a manifest whose url 404s — on a tag
# that is already published and cannot be moved.
XCF_ASSET="${XCF_NAME%.xcframework}-$VERSION.xcframework.zip"

# A 64-character lowercase hex string is the only thing SwiftPM accepts.
# `[[ =~ ]]` anchors against the WHOLE argument, not line-by-line like
# `grep` does (`grep -Eq '^...$'` matches if ANY line in the input matches —
# a checksum with an embedded newline still has one matching line, so a
# grep-based guard here would let a corrupt checksum through into the
# generated manifest, and `swift package dump-package` would only fail on
# the resulting tree, not on this script).
[[ "$CHECKSUM" =~ ^[0-9a-f]{64}$ ]] \
  || { echo "✗ checksum is not 64 hex chars: $CHECKSUM" >&2; exit 1; }

GENERATED_DIR="$SWIFT_DIR/Sources/Rovenue/Generated"
for f in RovenueFFI.swift RovenueFFI.h RovenueFFI.modulemap; do
  [ -s "$GENERATED_DIR/$f" ] \
    || { echo "✗ missing or empty uniffi binding: $GENERATED_DIR/$f" >&2
         echo "  Run packages/core-rs/scripts/build-bindings.sh first — the distribution package cannot ship without a real Swift binding." >&2
         exit 1; }
done

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR/Sources"
cp -R "$SWIFT_DIR/Sources/Rovenue" "$OUT_DIR/Sources/Rovenue"

cat > "$OUT_DIR/Package.swift" <<EOF
// swift-tools-version: 5.9
//
// GENERATED by packages/sdk-swift/scripts/generate-swift-dist.sh — do not edit.
// Source of truth: https://github.com/$REPO_SLUG (packages/sdk-swift)
import PackageDescription

let package = Package(
    name: "$POD_NAME",
    platforms: [.iOS(.v16), .macOS(.v12)],
    products: [
        .library(name: "$POD_NAME", targets: ["$POD_NAME"]),
    ],
    targets: [
        .binaryTarget(
            name: "RovenueFFI",
            url: "https://github.com/$REPO_SLUG/releases/download/sdk-swift-v$VERSION/$XCF_ASSET",
            checksum: "$CHECKSUM"
        ),
        .target(
            name: "$POD_NAME",
            dependencies: ["RovenueFFI"],
            path: "Sources/Rovenue",
            resources: [.copy("PrivacyInfo.xcprivacy")]
        ),
    ]
)
EOF

cat > "$OUT_DIR/README.md" <<EOF
# $POD_NAME (Swift Package)

Generated distribution package for the Rovenue Swift SDK. **Do not send pull
requests here** — the source lives at https://github.com/$REPO_SLUG under
\`packages/sdk-swift\`, and this repository is regenerated on every release.

\`\`\`swift
.package(url: "https://github.com/$REPO_SLUG-swift.git", from: "$VERSION"),
\`\`\`
EOF

echo "✓ $OUT_DIR (version $VERSION, checksum ${CHECKSUM:0:12}…)"
