#!/usr/bin/env bash
set -euo pipefail

# generate-swift-dist.sh — renders the standalone SwiftPM distribution package.
#
# External SPM consumers cannot depend on this monorepo: a tag here would carry
# a manifest whose binaryTarget points at a local path. They depend on a
# separate repository whose tags carry a manifest with a fixed url + checksum.
# That repository is generated output, never hand-edited.
#
# Usage: ./generate-swift-dist.sh <XCFRAMEWORK_ZIP_CHECKSUM> [OUT_DIR]

if [ $# -lt 1 ]; then
  echo "usage: $0 <XCFRAMEWORK_ZIP_CHECKSUM> [OUT_DIR]" >&2
  exit 2
fi

CHECKSUM="$1"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SWIFT_DIR="$(cd "$HERE/.." && pwd)"
CONFIG="$SWIFT_DIR/release.config.json"
OUT_DIR="${2:-$SWIFT_DIR/build/swift-dist}"

cfg() { ruby -rjson -e "print JSON.parse(File.read('$CONFIG'))['$1']"; }

REPO_SLUG="$(cfg repoSlug)"
VERSION="$(cfg version)"
POD_NAME="$(cfg podName)"

# A 64-character lowercase hex string is the only thing SwiftPM accepts.
echo "$CHECKSUM" | grep -Eq '^[0-9a-f]{64}$' \
  || { echo "✗ checksum is not 64 hex chars: $CHECKSUM" >&2; exit 1; }

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR/Sources"
cp -R "$SWIFT_DIR/Sources/Rovenue" "$OUT_DIR/Sources/Rovenue"

cat > "$OUT_DIR/Package.swift" <<EOF
// swift-tools-version: 5.9
//
// GENERATED by packages/sdk-swift/scripts/generate-swift-dist.sh — do not edit.
// Source of truth: https://github.com/$REPO_SLUG (packages/sdk-swift)
import PackageDescription

let package = Package(
    name: "$POD_NAME",
    platforms: [.iOS(.v16), .macOS(.v12)],
    products: [
        .library(name: "$POD_NAME", targets: ["$POD_NAME"]),
    ],
    targets: [
        .binaryTarget(
            name: "RovenueFFI",
            url: "https://github.com/$REPO_SLUG/releases/download/sdk-swift-v$VERSION/RovenueFFI-$VERSION.xcframework.zip",
            checksum: "$CHECKSUM"
        ),
        .target(
            name: "$POD_NAME",
            dependencies: ["RovenueFFI"],
            path: "Sources/Rovenue",
            resources: [.copy("PrivacyInfo.xcprivacy")]
        ),
    ]
)
EOF

cat > "$OUT_DIR/README.md" <<EOF
# $POD_NAME (Swift Package)

Generated distribution package for the Rovenue Swift SDK. **Do not send pull
requests here** — the source lives at https://github.com/$REPO_SLUG under
\`packages/sdk-swift\`, and this repository is regenerated on every release.

\`\`\`swift
.package(url: "https://github.com/$REPO_SLUG-swift.git", from: "$VERSION"),
\`\`\`
EOF

echo "✓ $OUT_DIR (version $VERSION, checksum ${CHECKSUM:0:12}…)"
