// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.rovenue.flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Mirrors the `"off" | "error" | "warn" | "info" | "debug" | "trace"`
 * log-level union used by `configure()` and `LogEntryDTO.level`.
 */
enum class RvLogLevel(val raw: Int) {
  OFF(0),
  ERROR(1),
  WARN(2),
  INFO(3),
  DEBUG(4),
  TRACE(5);

  companion object {
    fun ofRaw(raw: Int): RvLogLevel? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Mirrors `ProductTypeDTO` (`"subscription" | "consumable" |
 * "non_consumable"`).
 */
enum class RvProductType(val raw: Int) {
  SUBSCRIPTION(0),
  CONSUMABLE(1),
  NON_CONSUMABLE(2);

  companion object {
    fun ofRaw(raw: Int): RvProductType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Mirrors the `"open" | "background" | "close"` union accepted by
 * `recordSessionEvent`.
 */
enum class RvSessionEventKind(val raw: Int) {
  OPEN(0),
  BACKGROUND(1),
  CLOSE(2);

  companion object {
    fun ofRaw(raw: Int): RvSessionEventKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Mirrors `ProductCategoryDTO`. */
enum class RvProductCategory(val raw: Int) {
  SUBSCRIPTION(0),
  NON_SUBSCRIPTION(1);

  companion object {
    fun ofRaw(raw: Int): RvProductCategory? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Mirrors `PeriodUnitDTO`. */
enum class RvPeriodUnit(val raw: Int) {
  DAY(0),
  WEEK(1),
  MONTH(2),
  YEAR(3);

  companion object {
    fun ofRaw(raw: Int): RvPeriodUnit? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Mirrors `PaymentModeDTO`. */
enum class RvPaymentMode(val raw: Int) {
  FREE_TRIAL(0),
  PAY_AS_YOU_GO(1),
  PAY_UP_FRONT(2);

  companion object {
    fun ofRaw(raw: Int): RvPaymentMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Mirrors `DiscountTypeDTO`. */
enum class RvDiscountType(val raw: Int) {
  INTRODUCTORY(0),
  PROMOTIONAL(1),
  WIN_BACK(2);

  companion object {
    fun ofRaw(raw: Int): RvDiscountType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Mirrors `RecurrenceModeDTO`. */
enum class RvRecurrenceMode(val raw: Int) {
  INFINITE_RECURRING(0),
  FINITE_RECURRING(1),
  NON_RECURRING(2);

  companion object {
    fun ofRaw(raw: Int): RvRecurrenceMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Mirrors `PackageTypeDTO`. */
enum class RvPackageType(val raw: Int) {
  UNKNOWN(0),
  CUSTOM(1),
  LIFETIME(2),
  ANNUAL(3),
  SIX_MONTH(4),
  THREE_MONTH(5),
  TWO_MONTH(6),
  MONTHLY(7),
  WEEKLY(8);

  companion object {
    fun ofRaw(raw: Int): RvPackageType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Mirrors `ChangeEvent` (`packages/sdk-rn/src/types.ts`) — the native
 * `onChange` event payload's `event` discriminant.
 */
enum class RvChangeEventKind(val raw: Int) {
  ENTITLEMENTS_CHANGED(0),
  IDENTITY_CHANGED(1),
  VIRTUAL_CURRENCIES_CHANGED(2),
  REMOTE_CONFIG_CHANGED(3);

  companion object {
    fun ofRaw(raw: Int): RvChangeEventKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RvUser (
  val rovenueId: String,
  val appUserId: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RvUser {
      val rovenueId = pigeonVar_list[0] as String
      val appUserId = pigeonVar_list[1] as String?
      return RvUser(rovenueId, appUserId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      rovenueId,
      appUserId,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RvEntitlement (
  val id: String,
  val active: Boolean,
  val expiresAt: String? = null,
  val productId: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RvEntitlement {
      val id = pigeonVar_list[0] as String
      val active = pigeonVar_list[1] as Boolean
      val expiresAt = pigeonVar_list[2] as String?
      val productId = pigeonVar_list[3] as String?
      return RvEntitlement(id, active, expiresAt, productId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      active,
      expiresAt,
      productId,
    )
  }
}

/**
 * Mirrors `PeriodDTO`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RvPeriod (
  val value: Long,
  val unit: RvPeriodUnit,
  val iso8601: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RvPeriod {
      val value = pigeonVar_list[0] as Long
      val unit = pigeonVar_list[1] as RvPeriodUnit
      val iso8601 = pigeonVar_list[2] as String
      return RvPeriod(value, unit, iso8601)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      value,
      unit,
      iso8601,
    )
  }
}

/**
 * Mirrors `IntroPriceDTO`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RvIntroPrice (
  val price: Double? = null,
  val priceString: String? = null,
  val currencyCode: String? = null,
  val period: RvPeriod,
  val cycles: Long,
  val paymentMode: RvPaymentMode
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RvIntroPrice {
      val price = pigeonVar_list[0] as Double?
      val priceString = pigeonVar_list[1] as String?
      val currencyCode = pigeonVar_list[2] as String?
      val period = pigeonVar_list[3] as RvPeriod
      val cycles = pigeonVar_list[4] as Long
      val paymentMode = pigeonVar_list[5] as RvPaymentMode
      return RvIntroPrice(price, priceString, currencyCode, period, cycles, paymentMode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      price,
      priceString,
      currencyCode,
      period,
      cycles,
      paymentMode,
    )
  }
}

/**
 * Mirrors `DiscountDTO`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RvDiscount (
  val identifier: String? = null,
  val price: Double? = null,
  val priceString: String? = null,
  val currencyCode: String? = null,
  val period: RvPeriod,
  val numberOfPeriods: Long,
  val paymentMode: RvPaymentMode,
  val type: RvDiscountType
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RvDiscount {
      val identifier = pigeonVar_list[0] as String?
      val price = pigeonVar_list[1] as Double?
      val priceString = pigeonVar_list[2] as String?
      val currencyCode = pigeonVar_list[3] as String?
      val period = pigeonVar_list[4] as RvPeriod
      val numberOfPeriods = pigeonVar_list[5] as Long
      val paymentMode = pigeonVar_list[6] as RvPaymentMode
      val type = pigeonVar_list[7] as RvDiscountType
      return RvDiscount(identifier, price, priceString, currencyCode, period, numberOfPeriods, paymentMode, type)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      identifier,
      price,
      priceString,
      currencyCode,
      period,
      numberOfPeriods,
      paymentMode,
      type,
    )
  }
}

/**
 * Mirrors `PricingPhaseDTO`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RvPricingPhase (
  val price: Double? = null,
  val priceString: String? = null,
  val currencyCode: String? = null,
  val billingPeriod: RvPeriod,
  val billingCycleCount: Long? = null,
  val recurrenceMode: RvRecurrenceMode,
  val paymentMode: RvPaymentMode? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RvPricingPhase {
      val price = pigeonVar_list[0] as Double?
      val priceString = pigeonVar_list[1] as String?
      val currencyCode = pigeonVar_list[2] as String?
      val billingPeriod = pigeonVar_list[3] as RvPeriod
      val billingCycleCount = pigeonVar_list[4] as Long?
      val recurrenceMode = pigeonVar_list[5] as RvRecurrenceMode
      val paymentMode = pigeonVar_list[6] as RvPaymentMode?
      return RvPricingPhase(price, priceString, currencyCode, billingPeriod, billingCycleCount, recurrenceMode, paymentMode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      price,
      priceString,
      currencyCode,
      billingPeriod,
      billingCycleCount,
      recurrenceMode,
      paymentMode,
    )
  }
}

/**
 * Mirrors `SubscriptionOptionDTO`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RvSubscriptionOption (
  val id: String,
  val basePlanId: String? = null,
  val offerId: String? = null,
  val tags: List<String>,
  val isBasePlan: Boolean,
  val isPrepaid: Boolean,
  val pricingPhases: List<RvPricingPhase>,
  val freePhase: RvPricingPhase? = null,
  val introPhase: RvPricingPhase? = null,
  val fullPricePhase: RvPricingPhase? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RvSubscriptionOption {
      val id = pigeonVar_list[0] as String
      val basePlanId = pigeonVar_list[1] as String?
      val offerId = pigeonVar_list[2] as String?
      val tags = pigeonVar_list[3] as List<String>
      val isBasePlan = pigeonVar_list[4] as Boolean
      val isPrepaid = pigeonVar_list[5] as Boolean
      val pricingPhases = pigeonVar_list[6] as List<RvPricingPhase>
      val freePhase = pigeonVar_list[7] as RvPricingPhase?
      val introPhase = pigeonVar_list[8] as RvPricingPhase?
      val fullPricePhase = pigeonVar_list[9] as RvPricingPhase?
      return RvSubscriptionOption(id, basePlanId, offerId, tags, isBasePlan, isPrepaid, pricingPhases, freePhase, introPhase, fullPricePhase)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      basePlanId,
      offerId,
      tags,
      isBasePlan,
      isPrepaid,
      pricingPhases,
      freePhase,
      introPhase,
      fullPricePhase,
    )
  }
}

/**
 * Mirrors `StoreProductDTO`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RvStoreProduct (
  val id: String,
  val type: RvProductType,
  val productCategory: RvProductCategory,
  val displayName: String,
  val description: String? = null,
  val priceString: String? = null,
  val price: Double? = null,
  val currencyCode: String? = null,
  val subscriptionPeriod: RvPeriod? = null,
  val subscriptionGroupIdentifier: String? = null,
  val isFamilyShareable: Boolean,
  val introPrice: RvIntroPrice? = null,
  val discounts: List<RvDiscount>,
  val isEligibleForIntroOffer: Boolean? = null,
  val subscriptionOptions: List<RvSubscriptionOption>? = null,
  val defaultOption: RvSubscriptionOption? = null,
  val pricePerWeek: Double? = null,
  val pricePerMonth: Double? = null,
  val pricePerYear: Double? = null,
  val pricePerWeekString: String? = null,
  val pricePerMonthString: String? = null,
  val pricePerYearString: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RvStoreProduct {
      val id = pigeonVar_list[0] as String
      val type = pigeonVar_list[1] as RvProductType
      val productCategory = pigeonVar_list[2] as RvProductCategory
      val displayName = pigeonVar_list[3] as String
      val description = pigeonVar_list[4] as String?
      val priceString = pigeonVar_list[5] as String?
      val price = pigeonVar_list[6] as Double?
      val currencyCode = pigeonVar_list[7] as String?
      val subscriptionPeriod = pigeonVar_list[8] as RvPeriod?
      val subscriptionGroupIdentifier = pigeonVar_list[9] as String?
      val isFamilyShareable = pigeonVar_list[10] as Boolean
      val introPrice = pigeonVar_list[11] as RvIntroPrice?
      val discounts = pigeonVar_list[12] as List<RvDiscount>
      val isEligibleForIntroOffer = pigeonVar_list[13] as Boolean?
      val subscriptionOptions = pigeonVar_list[14] as List<RvSubscriptionOption>?
      val defaultOption = pigeonVar_list[15] as RvSubscriptionOption?
      val pricePerWeek = pigeonVar_list[16] as Double?
      val pricePerMonth = pigeonVar_list[17] as Double?
      val pricePerYear = pigeonVar_list[18] as Double?
      val pricePerWeekString = pigeonVar_list[19] as String?
      val pricePerMonthString = pigeonVar_list[20] as String?
      val pricePerYearString = pigeonVar_list[21] as String?
      return RvStoreProduct(id, type, productCategory, displayName, description, priceString, price, currencyCode, subscriptionPeriod, subscriptionGroupIdentifier, isFamilyShareable, introPrice, discounts, isEligibleForIntroOffer, subscriptionOptions, defaultOption, pricePerWeek, pricePerMonth, pricePerYear, pricePerWeekString, pricePerMonthString, pricePerYearString)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      type,
      productCategory,
      displayName,
      description,
      priceString,
      price,
      currencyCode,
      subscriptionPeriod,
      subscriptionGroupIdentifier,
      isFamilyShareable,
      introPrice,
      discounts,
      isEligibleForIntroOffer,
      subscriptionOptions,
      defaultOption,
      pricePerWeek,
      pricePerMonth,
      pricePerYear,
      pricePerWeekString,
      pricePerMonthString,
      pricePerYearString,
    )
  }
}

/**
 * Mirrors `PackageDTO`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RvPackage (
  val identifier: String,
  val packageType: RvPackageType? = null,
  val product: RvStoreProduct
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RvPackage {
      val identifier = pigeonVar_list[0] as String
      val packageType = pigeonVar_list[1] as RvPackageType?
      val product = pigeonVar_list[2] as RvStoreProduct
      return RvPackage(identifier, packageType, product)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      identifier,
      packageType,
      product,
    )
  }
}

/**
 * Mirrors `OfferingDTO`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RvOffering (
  val identifier: String,
  val isDefault: Boolean,
  val packages: List<RvPackage>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RvOffering {
      val identifier = pigeonVar_list[0] as String
      val isDefault = pigeonVar_list[1] as Boolean
      val packages = pigeonVar_list[2] as List<RvPackage>
      return RvOffering(identifier, isDefault, packages)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      identifier,
      isDefault,
      packages,
    )
  }
}

/**
 * Mirrors `OfferingsDTO`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RvOfferings (
  val current: String? = null,
  val offerings: List<RvOffering>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RvOfferings {
      val current = pigeonVar_list[0] as String?
      val offerings = pigeonVar_list[1] as List<RvOffering>
      return RvOfferings(current, offerings)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      current,
      offerings,
    )
  }
}

/**
 * Mirrors `PresentedContextDTO`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RvPresentedContext (
  val placementId: String,
  val paywallId: String,
  val variantId: String? = null,
  val experimentKey: String? = null,
  val revision: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RvPresentedContext {
      val placementId = pigeonVar_list[0] as String
      val paywallId = pigeonVar_list[1] as String
      val variantId = pigeonVar_list[2] as String?
      val experimentKey = pigeonVar_list[3] as String?
      val revision = pigeonVar_list[4] as Long
      return RvPresentedContext(placementId, paywallId, variantId, experimentKey, revision)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      placementId,
      paywallId,
      variantId,
      experimentKey,
      revision,
    )
  }
}

/**
 * Mirrors `PaywallDTO`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RvPaywall (
  val placementIdentifier: String,
  val placementRevision: Long,
  val paywallIdentifier: String? = null,
  val paywallName: String? = null,
  val configFormatVersion: Long,
  val remoteConfigJson: String? = null,
  val remoteConfigLocale: String? = null,
  val builderConfigJson: String? = null,
  val offering: RvOffering? = null,
  val presentedContext: RvPresentedContext? = null,
  val servedFromFallback: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RvPaywall {
      val placementIdentifier = pigeonVar_list[0] as String
      val placementRevision = pigeonVar_list[1] as Long
      val paywallIdentifier = pigeonVar_list[2] as String?
      val paywallName = pigeonVar_list[3] as String?
      val configFormatVersion = pigeonVar_list[4] as Long
      val remoteConfigJson = pigeonVar_list[5] as String?
      val remoteConfigLocale = pigeonVar_list[6] as String?
      val builderConfigJson = pigeonVar_list[7] as String?
      val offering = pigeonVar_list[8] as RvOffering?
      val presentedContext = pigeonVar_list[9] as RvPresentedContext?
      val servedFromFallback = pigeonVar_list[10] as Boolean
      return RvPaywall(placementIdentifier, placementRevision, paywallIdentifier, paywallName, configFormatVersion, remoteConfigJson, remoteConfigLocale, builderConfigJson, offering, presentedContext, servedFromFallback)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      placementIdentifier,
      placementRevision,
      paywallIdentifier,
      paywallName,
      configFormatVersion,
      remoteConfigJson,
      remoteConfigLocale,
      builderConfigJson,
      offering,
      presentedContext,
      servedFromFallback,
    )
  }
}

/**
 * Mirrors `ExperimentAssignmentDTO`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RvExperimentAssignment (
  val experimentId: String,
  val key: String,
  val variantId: String,
  val variantName: String,
  val valueJson: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RvExperimentAssignment {
      val experimentId = pigeonVar_list[0] as String
      val key = pigeonVar_list[1] as String
      val variantId = pigeonVar_list[2] as String
      val variantName = pigeonVar_list[3] as String
      val valueJson = pigeonVar_list[4] as String
      return RvExperimentAssignment(experimentId, key, variantId, variantName, valueJson)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      experimentId,
      key,
      variantId,
      variantName,
      valueJson,
    )
  }
}

/**
 * Mirrors `PurchaseResultDTO`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RvPurchaseResult (
  val entitlements: List<RvEntitlement>,
  val virtualCurrencies: Map<String, Long>,
  val productId: String,
  val storeTransactionId: String,
  val isDeferred: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RvPurchaseResult {
      val entitlements = pigeonVar_list[0] as List<RvEntitlement>
      val virtualCurrencies = pigeonVar_list[1] as Map<String, Long>
      val productId = pigeonVar_list[2] as String
      val storeTransactionId = pigeonVar_list[3] as String
      val isDeferred = pigeonVar_list[4] as Boolean
      return RvPurchaseResult(entitlements, virtualCurrencies, productId, storeTransactionId, isDeferred)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      entitlements,
      virtualCurrencies,
      productId,
      storeTransactionId,
      isDeferred,
    )
  }
}

/**
 * Mirrors the `{ subscriberId, funnelAnswersJson }` shape returned by
 * `claimFunnelToken` / `claimInstall` / `claimFromClipboard` and emitted by
 * the `onFunnelClaimResolved` native event.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RvFunnelClaim (
  val subscriberId: String,
  val funnelAnswersJson: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RvFunnelClaim {
      val subscriberId = pigeonVar_list[0] as String
      val funnelAnswersJson = pigeonVar_list[1] as String
      return RvFunnelClaim(subscriberId, funnelAnswersJson)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      subscriberId,
      funnelAnswersJson,
    )
  }
}

/**
 * Mirrors `claimInstall`'s `params` object — all fields optional.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RvClaimInstallParams (
  val platform: String? = null,
  val locale: String? = null,
  val timezone: String? = null,
  val screenDims: String? = null,
  val deviceModel: String? = null,
  val installReferrer: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RvClaimInstallParams {
      val platform = pigeonVar_list[0] as String?
      val locale = pigeonVar_list[1] as String?
      val timezone = pigeonVar_list[2] as String?
      val screenDims = pigeonVar_list[3] as String?
      val deviceModel = pigeonVar_list[4] as String?
      val installReferrer = pigeonVar_list[5] as String?
      return RvClaimInstallParams(platform, locale, timezone, screenDims, deviceModel, installReferrer)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      platform,
      locale,
      timezone,
      screenDims,
      deviceModel,
      installReferrer,
    )
  }
}

/**
 * Mirrors the native `onChange` event payload (`{ event: ChangeEvent }`).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RvChangeEvent (
  val kind: RvChangeEventKind
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RvChangeEvent {
      val kind = pigeonVar_list[0] as RvChangeEventKind
      return RvChangeEvent(kind)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      kind,
    )
  }
}

/**
 * Mirrors `LogEntryDTO`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RvLogRecord (
  val level: RvLogLevel,
  val message: String,
  val fields: Map<String, String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RvLogRecord {
      val level = pigeonVar_list[0] as RvLogLevel
      val message = pigeonVar_list[1] as String
      val fields = pigeonVar_list[2] as Map<String, String>
      return RvLogRecord(level, message, fields)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      level,
      message,
      fields,
    )
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RvLogLevel.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RvProductType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RvSessionEventKind.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RvProductCategory.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RvPeriodUnit.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RvPaymentMode.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RvDiscountType.ofRaw(it.toInt())
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RvRecurrenceMode.ofRaw(it.toInt())
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RvPackageType.ofRaw(it.toInt())
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RvChangeEventKind.ofRaw(it.toInt())
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RvUser.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RvEntitlement.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RvPeriod.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RvIntroPrice.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RvDiscount.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RvPricingPhase.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RvSubscriptionOption.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RvStoreProduct.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RvPackage.fromList(it)
        }
      }
      148.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RvOffering.fromList(it)
        }
      }
      149.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RvOfferings.fromList(it)
        }
      }
      150.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RvPresentedContext.fromList(it)
        }
      }
      151.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RvPaywall.fromList(it)
        }
      }
      152.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RvExperimentAssignment.fromList(it)
        }
      }
      153.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RvPurchaseResult.fromList(it)
        }
      }
      154.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RvFunnelClaim.fromList(it)
        }
      }
      155.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RvClaimInstallParams.fromList(it)
        }
      }
      156.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RvChangeEvent.fromList(it)
        }
      }
      157.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RvLogRecord.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is RvLogLevel -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is RvProductType -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is RvSessionEventKind -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is RvProductCategory -> {
        stream.write(132)
        writeValue(stream, value.raw)
      }
      is RvPeriodUnit -> {
        stream.write(133)
        writeValue(stream, value.raw)
      }
      is RvPaymentMode -> {
        stream.write(134)
        writeValue(stream, value.raw)
      }
      is RvDiscountType -> {
        stream.write(135)
        writeValue(stream, value.raw)
      }
      is RvRecurrenceMode -> {
        stream.write(136)
        writeValue(stream, value.raw)
      }
      is RvPackageType -> {
        stream.write(137)
        writeValue(stream, value.raw)
      }
      is RvChangeEventKind -> {
        stream.write(138)
        writeValue(stream, value.raw)
      }
      is RvUser -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is RvEntitlement -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is RvPeriod -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is RvIntroPrice -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is RvDiscount -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is RvPricingPhase -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is RvSubscriptionOption -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is RvStoreProduct -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is RvPackage -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      is RvOffering -> {
        stream.write(148)
        writeValue(stream, value.toList())
      }
      is RvOfferings -> {
        stream.write(149)
        writeValue(stream, value.toList())
      }
      is RvPresentedContext -> {
        stream.write(150)
        writeValue(stream, value.toList())
      }
      is RvPaywall -> {
        stream.write(151)
        writeValue(stream, value.toList())
      }
      is RvExperimentAssignment -> {
        stream.write(152)
        writeValue(stream, value.toList())
      }
      is RvPurchaseResult -> {
        stream.write(153)
        writeValue(stream, value.toList())
      }
      is RvFunnelClaim -> {
        stream.write(154)
        writeValue(stream, value.toList())
      }
      is RvClaimInstallParams -> {
        stream.write(155)
        writeValue(stream, value.toList())
      }
      is RvChangeEvent -> {
        stream.write(156)
        writeValue(stream, value.toList())
      }
      is RvLogRecord -> {
        stream.write(157)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface RovenueHostApi {
  fun configure(apiKey: String, baseUrl: String?, logLevel: RvLogLevel, appVersion: String?, environment: String?)
  fun shutdown()
  fun setForeground(foreground: Boolean)
  fun getVersion(): String
  fun getAppVersion(): String?
  fun currentUser(callback: (Result<RvUser>) -> Unit)
  fun identify(appUserId: String, callback: (Result<Unit>) -> Unit)
  fun logOut(callback: (Result<Unit>) -> Unit)
  fun entitlement(id: String, callback: (Result<RvEntitlement?>) -> Unit)
  fun entitlementsAll(callback: (Result<List<RvEntitlement>>) -> Unit)
  fun refreshEntitlements(callback: (Result<Unit>) -> Unit)
  fun virtualCurrencies(callback: (Result<Map<String, Long>>) -> Unit)
  fun virtualCurrency(code: String, callback: (Result<Long>) -> Unit)
  fun refreshVirtualCurrencies(callback: (Result<Unit>) -> Unit)
  fun getOfferings(callback: (Result<RvOfferings>) -> Unit)
  fun getPaywall(placementId: String, locale: String?, callback: (Result<RvPaywall?>) -> Unit)
  fun setFallbackPlacements(json: String, callback: (Result<Long>) -> Unit)
  fun purchase(productId: String, productType: RvProductType, promotionalOfferId: String?, basePlanId: String?, offerId: String?, callback: (Result<RvPurchaseResult>) -> Unit)
  fun restorePurchases(callback: (Result<RvPurchaseResult>) -> Unit)
  fun refreshRemoteConfig(callback: (Result<Unit>) -> Unit)
  fun remoteConfigBool(key: String, fallback: Boolean, callback: (Result<Boolean>) -> Unit)
  fun remoteConfigString(key: String, fallback: String, callback: (Result<String>) -> Unit)
  fun remoteConfigInt(key: String, fallback: Long, callback: (Result<Long>) -> Unit)
  fun remoteConfigDouble(key: String, fallback: Double, callback: (Result<Double>) -> Unit)
  fun remoteConfigJson(key: String, callback: (Result<String?>) -> Unit)
  fun remoteConfigKeys(callback: (Result<List<String>>) -> Unit)
  fun remoteConfigAllJson(callback: (Result<String>) -> Unit)
  fun experiment(key: String, callback: (Result<RvExperimentAssignment?>) -> Unit)
  fun experimentsAll(callback: (Result<List<RvExperimentAssignment>>) -> Unit)
  fun getAppAccountToken(callback: (Result<String>) -> Unit)
  fun recordSessionEvent(kind: RvSessionEventKind, occurredAt: String, durationMs: Long?, callback: (Result<Unit>) -> Unit)
  fun flushSessionEvents(callback: (Result<Long>) -> Unit)
  fun claimFunnelToken(token: String, callback: (Result<RvFunnelClaim>) -> Unit)
  fun claimInstall(params: RvClaimInstallParams, callback: (Result<RvFunnelClaim?>) -> Unit)
  fun claimViaEmail(email: String, callback: (Result<Unit>) -> Unit)
  fun claimFromClipboard(callback: (Result<RvFunnelClaim?>) -> Unit)
  fun installId(callback: (Result<String>) -> Unit)
  fun hasResolvedFunnelClaim(callback: (Result<Boolean>) -> Unit)
  fun track(envelopeJson: String, callback: (Result<Unit>) -> Unit)
  fun enqueuePaywallEvent(envelopeJson: String, callback: (Result<Unit>) -> Unit)
  fun setAttributes(attributes: Map<String, String?>, callback: (Result<Unit>) -> Unit)
  fun setEmail(email: String?, callback: (Result<Unit>) -> Unit)
  fun setDisplayName(name: String?, callback: (Result<Unit>) -> Unit)
  fun setPhoneNumber(phone: String?, callback: (Result<Unit>) -> Unit)
  fun setPushToken(token: String?, callback: (Result<Unit>) -> Unit)
  fun flushAttributes(callback: (Result<Long>) -> Unit)

  companion object {
    /** The codec used by RovenueHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `RovenueHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: RovenueHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.configure$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val apiKeyArg = args[0] as String
            val baseUrlArg = args[1] as String?
            val logLevelArg = args[2] as RvLogLevel
            val appVersionArg = args[3] as String?
            val environmentArg = args[4] as String?
            val wrapped: List<Any?> = try {
              api.configure(apiKeyArg, baseUrlArg, logLevelArg, appVersionArg, environmentArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.shutdown$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.shutdown()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.setForeground$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val foregroundArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setForeground(foregroundArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.getVersion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getVersion())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.getAppVersion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getAppVersion())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.currentUser$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.currentUser{ result: Result<RvUser> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.identify$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val appUserIdArg = args[0] as String
            api.identify(appUserIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.logOut$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.logOut{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.entitlement$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            api.entitlement(idArg) { result: Result<RvEntitlement?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.entitlementsAll$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.entitlementsAll{ result: Result<List<RvEntitlement>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.refreshEntitlements$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.refreshEntitlements{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.virtualCurrencies$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.virtualCurrencies{ result: Result<Map<String, Long>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.virtualCurrency$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val codeArg = args[0] as String
            api.virtualCurrency(codeArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.refreshVirtualCurrencies$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.refreshVirtualCurrencies{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.getOfferings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getOfferings{ result: Result<RvOfferings> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.getPaywall$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val placementIdArg = args[0] as String
            val localeArg = args[1] as String?
            api.getPaywall(placementIdArg, localeArg) { result: Result<RvPaywall?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.setFallbackPlacements$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val jsonArg = args[0] as String
            api.setFallbackPlacements(jsonArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.purchase$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val productIdArg = args[0] as String
            val productTypeArg = args[1] as RvProductType
            val promotionalOfferIdArg = args[2] as String?
            val basePlanIdArg = args[3] as String?
            val offerIdArg = args[4] as String?
            api.purchase(productIdArg, productTypeArg, promotionalOfferIdArg, basePlanIdArg, offerIdArg) { result: Result<RvPurchaseResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.restorePurchases$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.restorePurchases{ result: Result<RvPurchaseResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.refreshRemoteConfig$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.refreshRemoteConfig{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.remoteConfigBool$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val fallbackArg = args[1] as Boolean
            api.remoteConfigBool(keyArg, fallbackArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.remoteConfigString$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val fallbackArg = args[1] as String
            api.remoteConfigString(keyArg, fallbackArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.remoteConfigInt$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val fallbackArg = args[1] as Long
            api.remoteConfigInt(keyArg, fallbackArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.remoteConfigDouble$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val fallbackArg = args[1] as Double
            api.remoteConfigDouble(keyArg, fallbackArg) { result: Result<Double> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.remoteConfigJson$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            api.remoteConfigJson(keyArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.remoteConfigKeys$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.remoteConfigKeys{ result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.remoteConfigAllJson$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.remoteConfigAllJson{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.experiment$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            api.experiment(keyArg) { result: Result<RvExperimentAssignment?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.experimentsAll$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.experimentsAll{ result: Result<List<RvExperimentAssignment>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.getAppAccountToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getAppAccountToken{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.recordSessionEvent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val kindArg = args[0] as RvSessionEventKind
            val occurredAtArg = args[1] as String
            val durationMsArg = args[2] as Long?
            api.recordSessionEvent(kindArg, occurredAtArg, durationMsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.flushSessionEvents$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.flushSessionEvents{ result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.claimFunnelToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tokenArg = args[0] as String
            api.claimFunnelToken(tokenArg) { result: Result<RvFunnelClaim> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.claimInstall$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val paramsArg = args[0] as RvClaimInstallParams
            api.claimInstall(paramsArg) { result: Result<RvFunnelClaim?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.claimViaEmail$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val emailArg = args[0] as String
            api.claimViaEmail(emailArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.claimFromClipboard$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.claimFromClipboard{ result: Result<RvFunnelClaim?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.installId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.installId{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.hasResolvedFunnelClaim$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.hasResolvedFunnelClaim{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.track$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val envelopeJsonArg = args[0] as String
            api.track(envelopeJsonArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.enqueuePaywallEvent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val envelopeJsonArg = args[0] as String
            api.enqueuePaywallEvent(envelopeJsonArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.setAttributes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val attributesArg = args[0] as Map<String, String?>
            api.setAttributes(attributesArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.setEmail$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val emailArg = args[0] as String?
            api.setEmail(emailArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.setDisplayName$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nameArg = args[0] as String?
            api.setDisplayName(nameArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.setPhoneNumber$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val phoneArg = args[0] as String?
            api.setPhoneNumber(phoneArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.setPushToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tokenArg = args[0] as String?
            api.setPushToken(tokenArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.flushAttributes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.flushAttributes{ result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class RovenueFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by RovenueFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  fun onChange(eventArg: RvChangeEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueFlutterApi.onChange$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onLog(recordArg: RvLogRecord, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueFlutterApi.onLog$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(recordArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onFunnelClaim(claimArg: RvFunnelClaim, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueFlutterApi.onFunnelClaim$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(claimArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
