import type { Transaction, VolumeBar } from "./types";

/**
 * Hand-picked transaction fixtures spanning every type/status combination
 * the prototype shows off — purchases, renewals, refunds, trials, a
 * chargeback, a credit grant, and a couple of failures/disputes.
 */
export const TRANSACTIONS: ReadonlyArray<Transaction> = [
  {
    id: "tx_01HX9K2m",
    type: "purchase",
    sub: "sub_01HX9K2",
    user: "user_9f2a7b",
    product: "premium_yearly",
    store: "ios",
    gross: 79.99,
    fee: -12,
    tax: -6,
    net: 61.99,
    currency: "USD",
    country: "US",
    at: "2s ago",
    status: "paid",
    method: "Apple Pay · visa ending 4242",
  },
  {
    id: "tx_01HX9K1f",
    type: "renewal",
    sub: "sub_01HW7P4",
    user: "user_0fe92c",
    product: "premium_yearly",
    store: "ios",
    gross: 79.99,
    fee: -12,
    tax: -6,
    net: 61.99,
    currency: "USD",
    country: "NL",
    at: "18s ago",
    status: "paid",
    method: "App Store",
  },
  {
    id: "tx_01HX9Jyr",
    type: "refund",
    sub: "sub_01HV9Z2",
    user: "user_5b6c1f",
    product: "premium_monthly",
    store: "play",
    gross: -9.99,
    fee: 1.2,
    tax: 0.8,
    net: -7.99,
    currency: "USD",
    country: "BR",
    at: "1m ago",
    status: "paid",
    method: "Google Play · requested by user",
  },
  {
    id: "tx_01HX9Jq1",
    type: "trial",
    sub: "sub_01HX4R1",
    user: "user_4d0e11",
    product: "premium_monthly",
    store: "ios",
    gross: 0,
    fee: 0,
    tax: 0,
    net: 0,
    currency: "USD",
    country: "TR",
    at: "3m ago",
    status: "paid",
    method: "7-day free trial",
  },
  {
    id: "tx_01HX9J8k",
    type: "purchase",
    sub: "sub_01HX9J8",
    user: "user_beef91",
    product: "premium_monthly",
    store: "stripe",
    gross: 9.99,
    fee: -0.59,
    tax: -0.48,
    net: 8.92,
    currency: "USD",
    country: "BR",
    at: "5m ago",
    status: "paid",
    method: "Stripe · visa ending 0102",
  },
  {
    id: "tx_01HX9HbC",
    type: "renewal",
    sub: "sub_01HX2LD",
    user: "user_33b7ca",
    product: "pro_monthly",
    store: "ios",
    gross: 4.99,
    fee: -0.75,
    tax: -0.37,
    net: 3.87,
    currency: "USD",
    country: "KR",
    at: "8m ago",
    status: "paid",
    method: "App Store · stored",
  },
  {
    id: "tx_01HX9H2n",
    type: "chargeback",
    sub: "sub_01HW8AA",
    user: "user_4b10ff",
    product: "premium_yearly",
    store: "stripe",
    gross: -79.99,
    fee: 0,
    tax: 0,
    net: -79.99,
    currency: "USD",
    country: "US",
    at: "12m ago",
    status: "disputed",
    method: "Stripe dispute · fraudulent",
  },
  {
    id: "tx_01HX9Gw0",
    type: "credit",
    sub: "—",
    user: "user_9f2a7b",
    product: "credits_500",
    store: "ios",
    gross: 19.99,
    fee: -2.99,
    tax: -1.49,
    net: 15.51,
    currency: "USD",
    country: "US",
    at: "14m ago",
    status: "paid",
    method: "App Store · 500 credits granted",
  },
  {
    id: "tx_01HX9Ggy",
    type: "purchase",
    sub: "sub_01HX9Gg",
    user: "user_7a3c91",
    product: "pro_yearly",
    store: "ios",
    gross: 39.99,
    fee: -6,
    tax: -3,
    net: 30.99,
    currency: "USD",
    country: "GB",
    at: "21m ago",
    status: "paid",
    method: "App Store",
  },
  {
    id: "tx_01HX9FpX",
    type: "renewal",
    sub: "sub_01HW4KQ",
    user: "user_22fe0a",
    product: "starter_monthly",
    store: "play",
    gross: 1.99,
    fee: -0.3,
    tax: -0.15,
    net: 1.54,
    currency: "USD",
    country: "IN",
    at: "28m ago",
    status: "paid",
    method: "Google Play",
  },
  {
    id: "tx_01HX9FM3",
    type: "refund",
    sub: "sub_01HV0LL",
    user: "user_c14b00",
    product: "pro_monthly",
    store: "ios",
    gross: -4.99,
    fee: 0.75,
    tax: 0.37,
    net: -3.87,
    currency: "USD",
    country: "DE",
    at: "35m ago",
    status: "paid",
    method: "App Store · Apple review",
  },
  {
    id: "tx_01HX9F0p",
    type: "purchase",
    sub: "sub_01HX9F0",
    user: "user_ea9231",
    product: "premium_weekly",
    store: "ios",
    gross: 2.99,
    fee: -0.45,
    tax: -0.22,
    net: 2.32,
    currency: "USD",
    country: "AU",
    at: "42m ago",
    status: "paid",
    method: "App Store",
  },
  {
    id: "tx_01HX9Dyz",
    type: "renewal",
    sub: "sub_01HV9Pt",
    user: "user_e4f3aa",
    product: "pro_yearly",
    store: "ios",
    gross: 39.99,
    fee: -6,
    tax: -3,
    net: 30.99,
    currency: "USD",
    country: "FR",
    at: "1h ago",
    status: "paid",
    method: "App Store · stored",
  },
  {
    id: "tx_01HX9CqF",
    type: "purchase",
    sub: "sub_01HX9Cq",
    user: "user_bb0197",
    product: "premium_monthly",
    store: "stripe",
    gross: 9.99,
    fee: -0.59,
    tax: -0.48,
    net: 8.92,
    currency: "USD",
    country: "CA",
    at: "1h ago",
    status: "failed",
    method: "Stripe · card_declined",
  },
  {
    id: "tx_01HX9B8v",
    type: "chargeback",
    sub: "sub_01HX1C8",
    user: "user_ff0b8d",
    product: "starter_monthly",
    store: "play",
    gross: -1.99,
    fee: 0,
    tax: 0,
    net: -1.99,
    currency: "USD",
    country: "IN",
    at: "2h ago",
    status: "disputing",
    method: "Google Play · consumer disputed",
  },
];

/**
 * Deterministic 28-day stacked volume seeds. The values are picked from a
 * sine wave (so the bars look organic, not noisy) plus a small jitter.
 * We compute it once at module load — the dashboard is a prototype and
 * the bars don't need to mutate per render.
 */
export const VOLUME_SERIES: ReadonlyArray<VolumeBar> = Array.from({ length: 28 }, (_, i) => {
  const base = 320 + Math.sin(i / 3) * 80 + ((i * 53) % 40);
  return {
    day: i,
    purchases: base * 0.55,
    renewals: base * 0.38,
    refunds: ((i * 17) % 15) + 3,
    today: i === 27,
  };
});

export const VOLUME_MAX = Math.max(
  ...VOLUME_SERIES.map((b) => b.purchases + b.renewals + b.refunds),
);

/** Aggregate counts shown in the scope tabs. Counts here are display-only. */
export const SCOPE_TOTAL_COUNTS = {
  all: "14.2k",
  purchase: "4.2k",
  renewal: "9.6k",
  refund: "199",
  trial: "421",
  failed: "84",
} as const;

/** Total event count shown in the filter bar / paginator. */
export const TX_TOTAL_EVENTS = 14_281;

/** Per-store totals shown in the breakdown row under the volume graph. */
export const STORE_BREAKDOWN = [
  {
    store: "ios" as const,
    name: "App Store",
    revenue: "$142,840",
    fee: "$21.4k",
    feePercent: "15%",
    share: "57.5%",
  },
  {
    store: "play" as const,
    name: "Google Play",
    revenue: "$58,210",
    fee: "$8.7k",
    feePercent: "15%",
    share: "23.4%",
  },
  {
    store: "stripe" as const,
    name: "Stripe",
    revenue: "$38,442",
    fee: "$1.1k",
    feePercent: "2.9%",
    share: "15.5%",
  },
  {
    store: "web" as const,
    name: "Web / direct",
    revenue: "$8,700",
    fee: null,
    feePercent: null,
    share: "3.5%",
  },
];
