// =============================================================
// Rovenue edge-cache Worker
// =============================================================
//
// A thin reverse proxy in front of the origin API. It caches the SDK's
// hot, project-wide catalog read endpoint (offerings) at Cloudflare's
// edge so subscribers anywhere get sub-50ms catalog reads, while every
// write, webhook, and per-subscriber read falls through to the
// single-region origin unchanged.
//
// NOTE: /v1/config is deliberately NOT cached — it is always
// per-subscriber (requires subscriberId, evaluates flags/experiments)
// and even upserts the subscriber on GET, so it must always reach the
// origin.
//
// Caching rules (see isCacheable / shouldStore):
//   • Only GET requests to CACHEABLE_PREFIXES.
//   • BYPASS when the request identifies a subscriber
//     (x-rovenue-user-id header or ?subscriberId=) — those responses
//     run the experiment engine and are per-user.
//   • BYPASS when the origin response carries X-Rovenue-Experiment —
//     an OFFERING experiment overrode the catalog for this caller.
//   • Cache key is isolated per project (hash of the public Bearer
//     key) and per accessId, and versioned via Workers KV so a catalog
//     change purges the whole project globally and instantly.
//
// NOTE: `Env` is generated by `wrangler types` from wrangler.jsonc.
// The interface below is a placeholder so the file type-checks before
// you run it the first time — once you run `wrangler types`, delete it
// and let the generated ambient `Env` take over.
interface Env {
  CACHE_VERSIONS: KVNamespace;
  ORIGIN_URL: string;
  PURGE_SECRET: string;
}

const CACHEABLE_PREFIXES = ["/v1/offerings", "/v1/placements"];
const SUBSCRIBER_HEADER = "x-rovenue-user-id";
const EXPERIMENT_HEADER = "x-rovenue-experiment";
const PURGE_PATH = "/__edge/purge";

// Edge freshness. Short TTL keeps catalog edits visible within a
// minute even if a purge is missed; stale-while-revalidate serves
// instantly while a background refresh runs.
const EDGE_TTL_SECONDS = 60;
const STALE_WHILE_REVALIDATE_SECONDS = 300;

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);

    // Control plane: catalog-mutation purge. Not proxied to origin.
    if (url.pathname === PURGE_PATH) {
      return handlePurge(request, env);
    }

    // Everything proxies to the origin; we only add caching on top.
    const originUrl = new URL(url.pathname + url.search, env.ORIGIN_URL);
    const originRequest = new Request(originUrl.toString(), request);

    if (!isCacheable(request, url)) {
      return tag(await fetch(originRequest), "BYPASS");
    }

    const publicKey = bearerToken(request);
    if (!publicKey) {
      // Unauthenticated — let the origin return its 401 uncached.
      return tag(await fetch(originRequest), "BYPASS-NOAUTH");
    }

    const keyHash = await sha256Hex(publicKey);
    const version = await readVersion(env, keyHash);
    const cacheKey = buildCacheKey(url, keyHash, version);
    const cache = caches.default;

    const hit = await cache.match(cacheKey);
    if (hit) return tag(hit, "HIT");

    const originResponse = await fetch(originRequest);
    if (!shouldStore(request, originResponse)) {
      return tag(originResponse, "MISS-UNCACHEABLE");
    }

    const storable = makeStorable(originResponse, keyHash);
    // Cache write is post-response work — never block the client on it.
    ctx.waitUntil(cache.put(cacheKey, storable.clone()));
    return tag(storable, "MISS");
  },
} satisfies ExportedHandler<Env>;

// -------------------------------------------------------------
// Cacheability
// -------------------------------------------------------------

function isCacheable(request: Request, url: URL): boolean {
  if (request.method !== "GET") return false;
  if (!CACHEABLE_PREFIXES.some((p) => url.pathname.startsWith(p))) return false;
  // Per-subscriber identification makes the response personal (the
  // experiment engine may override the offering) — never cache it.
  if (request.headers.has(SUBSCRIBER_HEADER)) return false;
  if (url.searchParams.has("subscriberId")) return false;
  return true;
}

function shouldStore(request: Request, response: Response): boolean {
  if (request.method !== "GET") return false;
  if (response.status !== 200) return false;
  // An applied OFFERING experiment is per-caller — must not be shared.
  if (response.headers.has(EXPERIMENT_HEADER)) return false;
  const cc = response.headers.get("cache-control")?.toLowerCase() ?? "";
  if (cc.includes("no-store") || cc.includes("private")) return false;
  return true;
}

// -------------------------------------------------------------
// Cache key — isolated per project (key hash) + accessId + version
// -------------------------------------------------------------

function buildCacheKey(url: URL, keyHash: string, version: string): Request {
  // Synthetic, normalized key. accessId and locale are the only
  // meaningful cache dimensions on these endpoints; dropping other
  // query params stops junk params from fragmenting the cache.
  //
  // locale is normalized (lowercased, absent/empty collapse to the
  // same "none" marker) so `?locale=en` and `?locale=EN` share a key
  // while an unset locale doesn't fragment from an explicit empty one.
  // /v1/placements/:identifier?locale=xx returns locale-dependent
  // content — without this, differently-localized paywalls would
  // collide on one cache entry for up to EDGE_TTL_SECONDS.
  const keyUrl = new URL("https://edge-cache.rovenue.internal");
  keyUrl.pathname = url.pathname;
  const accessId = url.searchParams.get("accessId");
  if (accessId) keyUrl.searchParams.set("accessId", accessId);
  const locale = url.searchParams.get("locale")?.trim().toLowerCase() || "none";
  keyUrl.searchParams.set("locale", locale);
  keyUrl.searchParams.set("k", keyHash);
  keyUrl.searchParams.set("v", version);
  return new Request(keyUrl.toString(), { method: "GET" });
}

function makeStorable(response: Response, keyHash: string): Response {
  const headers = new Headers(response.headers);
  headers.set(
    "Cache-Control",
    `public, s-maxage=${EDGE_TTL_SECONDS}, stale-while-revalidate=${STALE_WHILE_REVALIDATE_SECONDS}`,
  );
  // Tag for optional Cloudflare cache-tag purge (Enterprise); harmless
  // elsewhere. Primary invalidation is the KV version bump.
  headers.set("Cache-Tag", `project:${keyHash}`);
  headers.delete("set-cookie");
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

// -------------------------------------------------------------
// Per-project cache version (Workers KV)
// -------------------------------------------------------------

function versionKvKey(keyHash: string): string {
  return `cachever:${keyHash}`;
}

async function readVersion(env: Env, keyHash: string): Promise<string> {
  // KV reads are edge-local and tier-cached; "0" is the pre-purge
  // baseline for a project that has never been invalidated.
  return (await env.CACHE_VERSIONS.get(versionKvKey(keyHash))) ?? "0";
}

async function bumpVersion(env: Env, keyHash: string): Promise<string> {
  // Monotonic timestamp avoids a read-modify-write race between
  // concurrent purges — any new value invalidates the old cache key.
  const next = Date.now().toString();
  await env.CACHE_VERSIONS.put(versionKvKey(keyHash), next);
  return next;
}

// -------------------------------------------------------------
// Purge control plane — called by the API on catalog mutation
// -------------------------------------------------------------
//
// POST /__edge/purge
//   header: X-Edge-Purge-Secret: <PURGE_SECRET>
//   body:   { "key": "<project public API key>" }
//
// Bumps the project's cache version so every cached offerings/config
// response for that key is missed on the next request worldwide.

async function handlePurge(request: Request, env: Env): Promise<Response> {
  if (request.method !== "POST") {
    return json({ error: { code: "method_not_allowed", message: "POST only" } }, 405);
  }
  const provided = request.headers.get("x-edge-purge-secret") ?? "";
  if (!timingSafeEqualStr(provided, env.PURGE_SECRET)) {
    return json({ error: { code: "unauthorized", message: "bad purge secret" } }, 401);
  }

  let body: { key?: unknown };
  try {
    body = (await request.json()) as { key?: unknown };
  } catch {
    return json({ error: { code: "bad_request", message: "invalid JSON body" } }, 400);
  }
  const publicKey = typeof body.key === "string" ? body.key : "";
  if (!publicKey) {
    return json({ error: { code: "bad_request", message: "`key` is required" } }, 400);
  }

  const keyHash = await sha256Hex(publicKey);
  const version = await bumpVersion(env, keyHash);
  // Structured log → searchable in the Observability dashboard.
  console.log(JSON.stringify({ msg: "edge.purge", keyHash, version }));
  return json({ data: { purged: true, version } }, 200);
}

// -------------------------------------------------------------
// Helpers
// -------------------------------------------------------------

function bearerToken(request: Request): string | null {
  const auth = request.headers.get("authorization");
  if (!auth) return null;
  const [scheme, token] = auth.split(" ");
  return scheme?.toLowerCase() === "bearer" && token ? token : null;
}

async function sha256Hex(input: string): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(input));
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

function timingSafeEqualStr(a: string, b: string): boolean {
  const ea = new TextEncoder().encode(a);
  const eb = new TextEncoder().encode(b);
  // timingSafeEqual throws on length mismatch; lengths are not the
  // secret, so a fast unequal-length reject is acceptable.
  if (ea.byteLength !== eb.byteLength) return false;
  return crypto.subtle.timingSafeEqual(ea, eb);
}

function tag(response: Response, state: string): Response {
  // Clone so we can mutate headers on an otherwise-immutable response.
  const out = new Response(response.body, response);
  out.headers.set("X-Rovenue-Edge", state);
  return out;
}

function json(body: unknown, status: number): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json" },
  });
}
