import type { FeatureFlag } from "./types";

export const FEATURE_FLAGS: ReadonlyArray<FeatureFlag> = [
  {
    key: "new_paywall_design",
    type: "bool",
    description:
      "Enable the rebuilt paywall with hero imagery and annual anchor.",
    enabled: true,
    killed: false,
    rolloutPct: 60,
    env: "prod",
    evalRate: 182.4,
    evals24h: 15_742_108,
    lastChanged: "14m ago",
    by: "furkan",
    tags: ["paywall", "mobile"],
    linkedExperiment: "paywall_v2_pricing",
    rules: [
      {
        type: "match",
        conditions: [
          { attribute: "country", op: "in", value: '["US","CA","GB","AU"]' },
          { attribute: "app_version", op: ">=", value: '"2.14.0"' },
        ],
        serve: "true",
        rolloutPct: 60,
      },
      {
        type: "match",
        conditions: [
          { attribute: "user.segment", op: "==", value: '"beta_testers"' },
        ],
        serve: "true",
        rolloutPct: 100,
      },
      { type: "default", serve: "false" },
    ],
    history: [
      {
        when: "14m ago",
        action: "Rollout increased",
        detail: "40% → 60% · furkan",
        tone: "primary",
      },
      {
        when: "2h ago",
        action: "Rollout increased",
        detail: "20% → 40% · furkan",
        tone: "primary",
      },
      {
        when: "1d ago",
        action: "Enabled in prod",
        detail: "10% canary · furkan",
        tone: "success",
      },
      {
        when: "3d ago",
        action: "Created",
        detail: "imported from spec · burak",
        tone: "neutral",
      },
    ],
  },
  {
    key: "paywall_headline_variant",
    type: "string",
    description: "Which headline copy to render on the onboarding paywall.",
    enabled: true,
    killed: false,
    rolloutPct: 100,
    env: "prod",
    evalRate: 94.1,
    evals24h: 8_121_440,
    lastChanged: "3h ago",
    by: "furkan",
    tags: ["copy", "experiment"],
    linkedExperiment: "offering_promo_card_copy",
    rules: [
      {
        type: "match",
        conditions: [
          { attribute: "user.locale", op: "starts_with", value: '"en"' },
        ],
        serve: "multivariate",
        rolloutPct: 100,
      },
      { type: "default", serve: '"save_40"' },
    ],
    variants: [
      { value: '"save_40"', pct: 34, color: "var(--color-rv-mute-500)" },
      { value: '"two_months_free"', pct: 33, color: "var(--color-rv-accent-500)" },
      { value: '"unlock_premium"', pct: 33, color: "var(--color-rv-violet)" },
    ],
    history: [
      {
        when: "3h ago",
        action: "Variant split rebalanced",
        detail: "50/50 → 34/33/33 · furkan",
        tone: "primary",
      },
      {
        when: "5d ago",
        action: "Enabled in prod",
        detail: "100% · furkan",
        tone: "success",
      },
    ],
  },
  {
    key: "allow_refund_self_service",
    type: "bool",
    description: "Let subscribers trigger refunds from the account screen.",
    enabled: false,
    killed: true,
    rolloutPct: 0,
    env: "prod",
    evalRate: 38.2,
    evals24h: 3_298_102,
    lastChanged: "6m ago",
    by: "burak",
    tags: ["risk", "billing"],
    rules: [{ type: "default", serve: "false" }],
    history: [
      {
        when: "6m ago",
        action: "Kill switch triggered",
        detail: "elevated refund rate alert · auto",
        tone: "danger",
      },
      {
        when: "2h ago",
        action: "Rollout increased",
        detail: "0% → 25% · burak",
        tone: "primary",
      },
      {
        when: "1d ago",
        action: "Created",
        detail: "furkan",
        tone: "neutral",
      },
    ],
  },
  {
    key: "credits_pack_500_visible",
    type: "bool",
    description: "Show the 500-credit pack in the credits purchase sheet.",
    enabled: true,
    killed: false,
    rolloutPct: 100,
    env: "prod",
    evalRate: 54.8,
    evals24h: 4_728_302,
    lastChanged: "2d ago",
    by: "furkan",
    tags: ["credits"],
    rules: [{ type: "default", serve: "true" }],
    history: [
      {
        when: "2d ago",
        action: "Rolled out to 100%",
        detail: "furkan",
        tone: "success",
      },
    ],
  },
  {
    key: "max_free_generations",
    type: "number",
    description: "Free AI generations per user per day before paywall.",
    enabled: true,
    killed: false,
    rolloutPct: 100,
    env: "prod",
    evalRate: 201.2,
    evals24h: 17_372_140,
    lastChanged: "8h ago",
    by: "burak",
    tags: ["paywall", "limits"],
    rules: [
      {
        type: "match",
        conditions: [
          { attribute: "user.plan", op: "==", value: '"free"' },
          { attribute: "account_age_days", op: "<", value: "7" },
        ],
        serve: "5",
      },
      {
        type: "match",
        conditions: [
          { attribute: "user.plan", op: "==", value: '"free"' },
        ],
        serve: "3",
      },
      { type: "default", serve: "1" },
    ],
    history: [
      {
        when: "8h ago",
        action: "Value changed",
        detail: "3 → 5 for new users · burak",
        tone: "primary",
      },
      {
        when: "8d ago",
        action: "Created",
        detail: "furkan",
        tone: "neutral",
      },
    ],
  },
  {
    key: "theme_accent_config",
    type: "json",
    description: "Tenant-level theme override (hex + radius + font variant).",
    enabled: true,
    killed: false,
    rolloutPct: 100,
    env: "prod",
    evalRate: 22.4,
    evals24h: 1_932_411,
    lastChanged: "5d ago",
    by: "furkan",
    tags: ["theming"],
    rules: [{ type: "default", serve: "json" }],
    history: [
      {
        when: "5d ago",
        action: "Created",
        detail: "furkan",
        tone: "neutral",
      },
    ],
  },
  {
    key: "android_14_biometric_fallback",
    type: "bool",
    description: "Use new biometric prompt on Android 14+ purchases.",
    enabled: true,
    killed: false,
    rolloutPct: 15,
    env: "prod",
    evalRate: 12.1,
    evals24h: 1_043_720,
    lastChanged: "22h ago",
    by: "burak",
    tags: ["android", "canary"],
    rules: [
      {
        type: "match",
        conditions: [
          { attribute: "platform", op: "==", value: '"android"' },
          { attribute: "os_version", op: ">=", value: "14" },
        ],
        serve: "true",
        rolloutPct: 15,
      },
      { type: "default", serve: "false" },
    ],
    history: [
      {
        when: "22h ago",
        action: "Canary started",
        detail: "15% of eligible · burak",
        tone: "success",
      },
    ],
  },
  {
    key: "legacy_v1_api_enabled",
    type: "bool",
    description: "Keep the v1 REST endpoints available for old clients.",
    enabled: true,
    killed: false,
    rolloutPct: 100,
    env: "prod",
    evalRate: 3.2,
    evals24h: 274_820,
    lastChanged: "32d ago",
    by: "furkan",
    tags: ["sdk", "legacy"],
    rules: [{ type: "default", serve: "true" }],
    history: [
      {
        when: "32d ago",
        action: "Created",
        detail: "migration scaffolding · furkan",
        tone: "neutral",
      },
    ],
  },
  {
    key: "beta_offline_mode",
    type: "bool",
    description: "Cache entitlements locally and re-sync on next launch.",
    enabled: false,
    killed: false,
    rolloutPct: 0,
    env: "staging",
    evalRate: 0,
    evals24h: 0,
    lastChanged: "1d ago",
    by: "furkan",
    tags: ["sdk", "staging"],
    rules: [{ type: "default", serve: "false" }],
    history: [
      {
        when: "1d ago",
        action: "Created",
        detail: "staging only · furkan",
        tone: "neutral",
      },
    ],
  },
];

export const TOTAL_EVALUATIONS_24H = "52.7M";

export const STALE_FLAGS_COUNT = 2;
