import type {
  Funnel,
  Session,
  ValidationIssue,
  Version,
} from "./types";

export const FUNNEL: Funnel = {
  id: "fn_main_quiz",
  name: "Fitness goal quiz",
  slug: "fitness-goal-quiz",
  status: "published",
  version: 14,
  draftDiffersFromPublished: true,
  theme: {
    primary: "#3B82F6",
    accent: "#8B5CF6",
    bg: "#FAFAFA",
    text: "#09090B",
    font: "Inter",
    logoUrl: "",
    logoLetter: "F",
  },
  settings: {
    iosUrl: "https://apps.apple.com/app/posely/id6478123456",
    androidUrl: "https://play.google.com/store/apps/details?id=com.posely",
    universalLinkDomain: "funnels.posely.app",
    deepLinkScheme: "posely",
    devMode: false,
  },
  pages: [
    {
      id: "pg_01",
      type: "single_choice",
      question_id: "goal",
      branchCount: 2,
      title: "What's your main goal?",
      subtitle: "Pick one — we use this to personalize your plan.",
      required: true,
      options: [
        { label: "Lose weight", value: "lose_weight" },
        { label: "Build muscle", value: "build_muscle" },
        { label: "Get healthier", value: "get_healthy" },
        { label: "Just exploring", value: "just_exploring" },
      ],
    },
    {
      id: "pg_02",
      type: "single_choice",
      question_id: "activity_level",
      title: "How active are you right now?",
      required: true,
      options: [
        { label: "Barely move", value: "sedentary" },
        { label: "Walk most days", value: "light" },
        { label: "Work out 1–3x / week", value: "moderate" },
        { label: "Train 4+ times / week", value: "high" },
      ],
    },
    {
      id: "pg_03",
      type: "number_input",
      question_id: "age",
      title: "How old are you?",
      subtitle: "We tune intensity and recovery based on age.",
      required: true,
      min: 13,
      max: 99,
      step: 1,
      suffix: "years",
    },
    {
      id: "pg_04",
      type: "slider",
      question_id: "goal_weight_kg",
      title: "What weight would you like to reach?",
      required: true,
      min: 40,
      max: 150,
      step: 1,
      format: "{{value}} kg",
      branchCount: 1,
      validation_errors: 1,
    },
    {
      id: "pg_05",
      type: "multi_choice",
      question_id: "blockers",
      title: "What gets in the way?",
      subtitle: "Pick up to 3.",
      required: false,
      max_selections: 3,
      options: [
        { label: "No time", value: "no_time" },
        { label: "Don't enjoy it", value: "no_enjoy" },
        { label: "Hard to stay consistent", value: "consistency" },
        { label: "Injury / health concerns", value: "injury" },
        { label: "Cost", value: "cost" },
      ],
    },
    {
      id: "pg_06",
      type: "loading",
      title: "Building your plan…",
      duration: 4500,
      steps: [
        "Analyzing your goal…",
        "Matching workouts…",
        "Tuning intensity…",
        "Finalizing your plan",
      ],
    },
    {
      id: "pg_07",
      type: "result",
      title: "Your {{goal}} plan",
      body: "Based on your answers we built a {{activity_level}}-friendly plan. Most members reach their goal in 12–14 weeks.",
    },
    {
      id: "pg_08",
      type: "paywall",
      title: "Unlock your plan",
      productId: "prod_pro_annual",
      trial: 7,
      headline: "Start your 7-day free trial",
      benefits: [
        "Personalized weekly workouts",
        "AI form check on every set",
        "Adaptive recovery & rest days",
        "Cancel anytime",
      ],
    },
    {
      id: "pg_09",
      type: "success",
      title: "You're all set!",
      body: "Open the app to start your first workout — we've already signed you in.",
      cta: "Open Posely",
    },
  ],
  rules: {
    pg_01: [
      {
        id: "r1",
        combinator: "all",
        clauses: [{ qid: "goal", op: "equals", value: "just_exploring" }],
        goto: "pg_08",
      },
    ],
    pg_04: [
      {
        id: "r1",
        combinator: "all",
        clauses: [
          { qid: "goal", op: "equals", value: "build_muscle" },
          { qid: "age", op: ">=", value: 40 },
        ],
        goto: "pg_05",
      },
      {
        id: "r2",
        combinator: "all",
        clauses: [{ qid: "goal_weight_kg", op: "between", value: [40, 60] }],
        goto: "pg_DELETED",
      },
    ],
  },
  default_next: {
    pg_01: null,
    pg_02: null,
    pg_03: null,
    pg_04: null,
    pg_05: null,
    pg_06: null,
    pg_07: null,
    pg_08: "pg_09",
    pg_09: null,
  },
};

export const VALIDATION_ISSUES: ReadonlyArray<ValidationIssue> = [
  {
    kind: "error",
    where: "pg_04 · rule #2",
    title: "Broken goto reference",
    desc: "Rule sends visitors to pg_DELETED, which no longer exists. Pick a valid target or delete this rule.",
    fix: "Open rule",
  },
  {
    kind: "warning",
    where: "pg_05",
    title: "Page may be unreachable",
    desc: "pg_04 has a rule that skips pg_05 when goal_weight_kg is between 40 and 60. Visitors matching that branch will never see this page.",
    fix: "Inspect graph",
  },
  {
    kind: "warning",
    where: "theme",
    title: "Low text contrast",
    desc: "Primary on background passes WCAG AA. But accent (#8B5CF6) on bg (#FAFAFA) has a 4.42:1 ratio — borderline for body copy.",
    fix: "Open Theme",
  },
];

export const VERSIONS: ReadonlyArray<Version> = [
  {
    num: 14,
    when: "2 days ago",
    date: "Apr 18, 2026 · 14:22",
    who: "furkan",
    pages: 9,
    isCurrent: true,
    notes:
      'Added "Just exploring" branch that skips the goal screen straight to the paywall. Tweaked paywall copy.',
  },
  {
    num: 13,
    when: "6 days ago",
    date: "Apr 14, 2026 · 09:08",
    who: "tess",
    pages: 9,
    notes: "Replaced free-text age with number input. Bumped slider step from 5 to 1 kg.",
  },
  {
    num: 12,
    when: "12 days ago",
    date: "Apr 8, 2026 · 16:55",
    who: "furkan",
    pages: 8,
    notes:
      "Added 4-step loading screen between blockers and result. Improves perceived value of the result page.",
  },
  {
    num: 11,
    when: "21 days ago",
    date: "Mar 30, 2026 · 11:01",
    who: "aris",
    pages: 8,
    notes:
      "Initial 8-page flow. Single-choice goal, activity level, age, weight, blockers, result, paywall, success.",
  },
];

export const SESSIONS: ReadonlyArray<Session> = [
  {
    id: "sess_h7G3vKLm",
    started: "Apr 20, 14:38",
    last: "12s ago",
    state: "in_progress",
    currentPage: "pg_04 · Goal weight",
    utm: "tiktok",
    answers: 3,
    paid: null,
  },
  {
    id: "sess_9pX2RtBa",
    started: "Apr 20, 14:32",
    last: "1m ago",
    state: "paid",
    currentPage: "pg_09 · Success",
    utm: "meta",
    answers: 5,
    paid: "cus_NkLM8q",
  },
  {
    id: "sess_Q4mFs1Rv",
    started: "Apr 20, 14:28",
    last: "4m ago",
    state: "in_progress",
    currentPage: "pg_06 · Loading",
    utm: "organic",
    answers: 5,
    paid: null,
  },
  {
    id: "sess_8nDpW3qX",
    started: "Apr 20, 14:22",
    last: "8m ago",
    state: "paid",
    currentPage: "pg_09 · Success",
    utm: "tiktok",
    answers: 5,
    paid: "cus_NkM2pq",
  },
  {
    id: "sess_aR7Gb2Vc",
    started: "Apr 20, 14:14",
    last: "17m ago",
    state: "abandoned",
    currentPage: "pg_02 · Activity",
    utm: "google",
    answers: 1,
    paid: null,
  },
  {
    id: "sess_3kPjQ8Wl",
    started: "Apr 20, 14:11",
    last: "20m ago",
    state: "completed",
    currentPage: "pg_09 · Success",
    utm: "meta",
    answers: 5,
    paid: null,
  },
  {
    id: "sess_Z2mNd4xH",
    started: "Apr 20, 14:06",
    last: "24m ago",
    state: "abandoned",
    currentPage: "pg_08 · Paywall",
    utm: "tiktok",
    answers: 5,
    paid: null,
  },
  {
    id: "sess_K9wBs5Tn",
    started: "Apr 20, 13:58",
    last: "32m ago",
    state: "paid",
    currentPage: "pg_09 · Success",
    utm: "meta",
    answers: 5,
    paid: "cus_Nh3KrA",
  },
];
