// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

/// Mirrors the `"off" | "error" | "warn" | "info" | "debug" | "trace"`
/// log-level union used by `configure()` and `LogEntryDTO.level`.
enum RvLogLevel {
  off,
  error,
  warn,
  info,
  debug,
  trace,
}

/// Mirrors `ProductTypeDTO` (`"subscription" | "consumable" |
/// "non_consumable"`).
enum RvProductType {
  subscription,
  consumable,
  nonConsumable,
}

/// Mirrors the `"open" | "background" | "close"` union accepted by
/// `recordSessionEvent`.
enum RvSessionEventKind {
  open,
  background,
  close,
}

/// Mirrors `ProductCategoryDTO`.
enum RvProductCategory {
  subscription,
  nonSubscription,
}

/// Mirrors `PeriodUnitDTO`.
enum RvPeriodUnit {
  day,
  week,
  month,
  year,
}

/// Mirrors `PaymentModeDTO`.
enum RvPaymentMode {
  freeTrial,
  payAsYouGo,
  payUpFront,
}

/// Mirrors `DiscountTypeDTO`.
enum RvDiscountType {
  introductory,
  promotional,
  winBack,
}

/// Mirrors `RecurrenceModeDTO`.
enum RvRecurrenceMode {
  infiniteRecurring,
  finiteRecurring,
  nonRecurring,
}

/// Mirrors `PackageTypeDTO`.
enum RvPackageType {
  unknown,
  custom,
  lifetime,
  annual,
  sixMonth,
  threeMonth,
  twoMonth,
  monthly,
  weekly,
}

/// Mirrors `ChangeEvent` (`packages/sdk-rn/src/types.ts`) — the native
/// `onChange` event payload's `event` discriminant.
enum RvChangeEventKind {
  entitlementsChanged,
  identityChanged,
  virtualCurrenciesChanged,
  remoteConfigChanged,
}

class RvUser {
  RvUser({
    required this.rovenueId,
    this.appUserId,
  });

  String rovenueId;

  String? appUserId;

  Object encode() {
    return <Object?>[
      rovenueId,
      appUserId,
    ];
  }

  static RvUser decode(Object result) {
    result as List<Object?>;
    return RvUser(
      rovenueId: result[0]! as String,
      appUserId: result[1] as String?,
    );
  }
}

class RvEntitlement {
  RvEntitlement({
    required this.id,
    required this.active,
    this.expiresAt,
    this.productId,
  });

  String id;

  bool active;

  String? expiresAt;

  String? productId;

  Object encode() {
    return <Object?>[
      id,
      active,
      expiresAt,
      productId,
    ];
  }

  static RvEntitlement decode(Object result) {
    result as List<Object?>;
    return RvEntitlement(
      id: result[0]! as String,
      active: result[1]! as bool,
      expiresAt: result[2] as String?,
      productId: result[3] as String?,
    );
  }
}

/// Mirrors `PeriodDTO`.
class RvPeriod {
  RvPeriod({
    required this.value,
    required this.unit,
    required this.iso8601,
  });

  int value;

  RvPeriodUnit unit;

  String iso8601;

  Object encode() {
    return <Object?>[
      value,
      unit,
      iso8601,
    ];
  }

  static RvPeriod decode(Object result) {
    result as List<Object?>;
    return RvPeriod(
      value: result[0]! as int,
      unit: result[1]! as RvPeriodUnit,
      iso8601: result[2]! as String,
    );
  }
}

/// Mirrors `IntroPriceDTO`.
class RvIntroPrice {
  RvIntroPrice({
    this.price,
    this.priceString,
    this.currencyCode,
    required this.period,
    required this.cycles,
    required this.paymentMode,
  });

  double? price;

  String? priceString;

  String? currencyCode;

  RvPeriod period;

  int cycles;

  RvPaymentMode paymentMode;

  Object encode() {
    return <Object?>[
      price,
      priceString,
      currencyCode,
      period,
      cycles,
      paymentMode,
    ];
  }

  static RvIntroPrice decode(Object result) {
    result as List<Object?>;
    return RvIntroPrice(
      price: result[0] as double?,
      priceString: result[1] as String?,
      currencyCode: result[2] as String?,
      period: result[3]! as RvPeriod,
      cycles: result[4]! as int,
      paymentMode: result[5]! as RvPaymentMode,
    );
  }
}

/// Mirrors `DiscountDTO`.
class RvDiscount {
  RvDiscount({
    this.identifier,
    this.price,
    this.priceString,
    this.currencyCode,
    required this.period,
    required this.numberOfPeriods,
    required this.paymentMode,
    required this.type,
  });

  String? identifier;

  double? price;

  String? priceString;

  String? currencyCode;

  RvPeriod period;

  int numberOfPeriods;

  RvPaymentMode paymentMode;

  RvDiscountType type;

  Object encode() {
    return <Object?>[
      identifier,
      price,
      priceString,
      currencyCode,
      period,
      numberOfPeriods,
      paymentMode,
      type,
    ];
  }

  static RvDiscount decode(Object result) {
    result as List<Object?>;
    return RvDiscount(
      identifier: result[0] as String?,
      price: result[1] as double?,
      priceString: result[2] as String?,
      currencyCode: result[3] as String?,
      period: result[4]! as RvPeriod,
      numberOfPeriods: result[5]! as int,
      paymentMode: result[6]! as RvPaymentMode,
      type: result[7]! as RvDiscountType,
    );
  }
}

/// Mirrors `PricingPhaseDTO`.
class RvPricingPhase {
  RvPricingPhase({
    this.price,
    this.priceString,
    this.currencyCode,
    required this.billingPeriod,
    this.billingCycleCount,
    required this.recurrenceMode,
    this.paymentMode,
  });

  double? price;

  String? priceString;

  String? currencyCode;

  RvPeriod billingPeriod;

  int? billingCycleCount;

  RvRecurrenceMode recurrenceMode;

  RvPaymentMode? paymentMode;

  Object encode() {
    return <Object?>[
      price,
      priceString,
      currencyCode,
      billingPeriod,
      billingCycleCount,
      recurrenceMode,
      paymentMode,
    ];
  }

  static RvPricingPhase decode(Object result) {
    result as List<Object?>;
    return RvPricingPhase(
      price: result[0] as double?,
      priceString: result[1] as String?,
      currencyCode: result[2] as String?,
      billingPeriod: result[3]! as RvPeriod,
      billingCycleCount: result[4] as int?,
      recurrenceMode: result[5]! as RvRecurrenceMode,
      paymentMode: result[6] as RvPaymentMode?,
    );
  }
}

/// Mirrors `SubscriptionOptionDTO`.
class RvSubscriptionOption {
  RvSubscriptionOption({
    required this.id,
    this.basePlanId,
    this.offerId,
    required this.tags,
    required this.isBasePlan,
    required this.isPrepaid,
    required this.pricingPhases,
    this.freePhase,
    this.introPhase,
    this.fullPricePhase,
  });

  String id;

  String? basePlanId;

  String? offerId;

  List<String> tags;

  bool isBasePlan;

  bool isPrepaid;

  List<RvPricingPhase> pricingPhases;

  RvPricingPhase? freePhase;

  RvPricingPhase? introPhase;

  RvPricingPhase? fullPricePhase;

  Object encode() {
    return <Object?>[
      id,
      basePlanId,
      offerId,
      tags,
      isBasePlan,
      isPrepaid,
      pricingPhases,
      freePhase,
      introPhase,
      fullPricePhase,
    ];
  }

  static RvSubscriptionOption decode(Object result) {
    result as List<Object?>;
    return RvSubscriptionOption(
      id: result[0]! as String,
      basePlanId: result[1] as String?,
      offerId: result[2] as String?,
      tags: (result[3] as List<Object?>?)!.cast<String>(),
      isBasePlan: result[4]! as bool,
      isPrepaid: result[5]! as bool,
      pricingPhases: (result[6] as List<Object?>?)!.cast<RvPricingPhase>(),
      freePhase: result[7] as RvPricingPhase?,
      introPhase: result[8] as RvPricingPhase?,
      fullPricePhase: result[9] as RvPricingPhase?,
    );
  }
}

/// Mirrors `StoreProductDTO`.
class RvStoreProduct {
  RvStoreProduct({
    required this.id,
    required this.type,
    required this.productCategory,
    required this.displayName,
    this.description,
    this.priceString,
    this.price,
    this.currencyCode,
    this.subscriptionPeriod,
    this.subscriptionGroupIdentifier,
    required this.isFamilyShareable,
    this.introPrice,
    required this.discounts,
    this.isEligibleForIntroOffer,
    this.subscriptionOptions,
    this.defaultOption,
    this.pricePerWeek,
    this.pricePerMonth,
    this.pricePerYear,
    this.pricePerWeekString,
    this.pricePerMonthString,
    this.pricePerYearString,
  });

  String id;

  RvProductType type;

  RvProductCategory productCategory;

  String displayName;

  String? description;

  String? priceString;

  double? price;

  String? currencyCode;

  RvPeriod? subscriptionPeriod;

  String? subscriptionGroupIdentifier;

  bool isFamilyShareable;

  RvIntroPrice? introPrice;

  List<RvDiscount> discounts;

  bool? isEligibleForIntroOffer;

  List<RvSubscriptionOption>? subscriptionOptions;

  RvSubscriptionOption? defaultOption;

  double? pricePerWeek;

  double? pricePerMonth;

  double? pricePerYear;

  String? pricePerWeekString;

  String? pricePerMonthString;

  String? pricePerYearString;

  Object encode() {
    return <Object?>[
      id,
      type,
      productCategory,
      displayName,
      description,
      priceString,
      price,
      currencyCode,
      subscriptionPeriod,
      subscriptionGroupIdentifier,
      isFamilyShareable,
      introPrice,
      discounts,
      isEligibleForIntroOffer,
      subscriptionOptions,
      defaultOption,
      pricePerWeek,
      pricePerMonth,
      pricePerYear,
      pricePerWeekString,
      pricePerMonthString,
      pricePerYearString,
    ];
  }

  static RvStoreProduct decode(Object result) {
    result as List<Object?>;
    return RvStoreProduct(
      id: result[0]! as String,
      type: result[1]! as RvProductType,
      productCategory: result[2]! as RvProductCategory,
      displayName: result[3]! as String,
      description: result[4] as String?,
      priceString: result[5] as String?,
      price: result[6] as double?,
      currencyCode: result[7] as String?,
      subscriptionPeriod: result[8] as RvPeriod?,
      subscriptionGroupIdentifier: result[9] as String?,
      isFamilyShareable: result[10]! as bool,
      introPrice: result[11] as RvIntroPrice?,
      discounts: (result[12] as List<Object?>?)!.cast<RvDiscount>(),
      isEligibleForIntroOffer: result[13] as bool?,
      subscriptionOptions: (result[14] as List<Object?>?)?.cast<RvSubscriptionOption>(),
      defaultOption: result[15] as RvSubscriptionOption?,
      pricePerWeek: result[16] as double?,
      pricePerMonth: result[17] as double?,
      pricePerYear: result[18] as double?,
      pricePerWeekString: result[19] as String?,
      pricePerMonthString: result[20] as String?,
      pricePerYearString: result[21] as String?,
    );
  }
}

/// Mirrors `PackageDTO`.
class RvPackage {
  RvPackage({
    required this.identifier,
    this.packageType,
    required this.product,
  });

  String identifier;

  RvPackageType? packageType;

  RvStoreProduct product;

  Object encode() {
    return <Object?>[
      identifier,
      packageType,
      product,
    ];
  }

  static RvPackage decode(Object result) {
    result as List<Object?>;
    return RvPackage(
      identifier: result[0]! as String,
      packageType: result[1] as RvPackageType?,
      product: result[2]! as RvStoreProduct,
    );
  }
}

/// Mirrors `OfferingDTO`.
class RvOffering {
  RvOffering({
    required this.identifier,
    required this.isDefault,
    required this.packages,
  });

  String identifier;

  bool isDefault;

  List<RvPackage> packages;

  Object encode() {
    return <Object?>[
      identifier,
      isDefault,
      packages,
    ];
  }

  static RvOffering decode(Object result) {
    result as List<Object?>;
    return RvOffering(
      identifier: result[0]! as String,
      isDefault: result[1]! as bool,
      packages: (result[2] as List<Object?>?)!.cast<RvPackage>(),
    );
  }
}

/// Mirrors `OfferingsDTO`.
class RvOfferings {
  RvOfferings({
    this.current,
    required this.offerings,
  });

  String? current;

  List<RvOffering> offerings;

  Object encode() {
    return <Object?>[
      current,
      offerings,
    ];
  }

  static RvOfferings decode(Object result) {
    result as List<Object?>;
    return RvOfferings(
      current: result[0] as String?,
      offerings: (result[1] as List<Object?>?)!.cast<RvOffering>(),
    );
  }
}

/// Mirrors `PresentedContextDTO`.
class RvPresentedContext {
  RvPresentedContext({
    required this.placementId,
    required this.paywallId,
    this.variantId,
    this.experimentKey,
    required this.revision,
  });

  String placementId;

  String paywallId;

  String? variantId;

  String? experimentKey;

  int revision;

  Object encode() {
    return <Object?>[
      placementId,
      paywallId,
      variantId,
      experimentKey,
      revision,
    ];
  }

  static RvPresentedContext decode(Object result) {
    result as List<Object?>;
    return RvPresentedContext(
      placementId: result[0]! as String,
      paywallId: result[1]! as String,
      variantId: result[2] as String?,
      experimentKey: result[3] as String?,
      revision: result[4]! as int,
    );
  }
}

/// Mirrors `PaywallDTO`.
class RvPaywall {
  RvPaywall({
    required this.placementIdentifier,
    required this.placementRevision,
    this.paywallIdentifier,
    this.paywallName,
    required this.configFormatVersion,
    this.remoteConfigJson,
    this.remoteConfigLocale,
    this.builderConfigJson,
    this.offering,
    this.presentedContext,
    required this.servedFromFallback,
  });

  String placementIdentifier;

  int placementRevision;

  String? paywallIdentifier;

  String? paywallName;

  int configFormatVersion;

  String? remoteConfigJson;

  String? remoteConfigLocale;

  String? builderConfigJson;

  RvOffering? offering;

  RvPresentedContext? presentedContext;

  bool servedFromFallback;

  Object encode() {
    return <Object?>[
      placementIdentifier,
      placementRevision,
      paywallIdentifier,
      paywallName,
      configFormatVersion,
      remoteConfigJson,
      remoteConfigLocale,
      builderConfigJson,
      offering,
      presentedContext,
      servedFromFallback,
    ];
  }

  static RvPaywall decode(Object result) {
    result as List<Object?>;
    return RvPaywall(
      placementIdentifier: result[0]! as String,
      placementRevision: result[1]! as int,
      paywallIdentifier: result[2] as String?,
      paywallName: result[3] as String?,
      configFormatVersion: result[4]! as int,
      remoteConfigJson: result[5] as String?,
      remoteConfigLocale: result[6] as String?,
      builderConfigJson: result[7] as String?,
      offering: result[8] as RvOffering?,
      presentedContext: result[9] as RvPresentedContext?,
      servedFromFallback: result[10]! as bool,
    );
  }
}

/// Mirrors `ExperimentAssignmentDTO`.
class RvExperimentAssignment {
  RvExperimentAssignment({
    required this.experimentId,
    required this.key,
    required this.variantId,
    required this.variantName,
    required this.valueJson,
  });

  String experimentId;

  String key;

  String variantId;

  String variantName;

  String valueJson;

  Object encode() {
    return <Object?>[
      experimentId,
      key,
      variantId,
      variantName,
      valueJson,
    ];
  }

  static RvExperimentAssignment decode(Object result) {
    result as List<Object?>;
    return RvExperimentAssignment(
      experimentId: result[0]! as String,
      key: result[1]! as String,
      variantId: result[2]! as String,
      variantName: result[3]! as String,
      valueJson: result[4]! as String,
    );
  }
}

/// Mirrors `PurchaseResultDTO`.
class RvPurchaseResult {
  RvPurchaseResult({
    required this.entitlements,
    required this.virtualCurrencies,
    required this.productId,
    required this.storeTransactionId,
    required this.isDeferred,
  });

  List<RvEntitlement> entitlements;

  Map<String, int> virtualCurrencies;

  String productId;

  String storeTransactionId;

  bool isDeferred;

  Object encode() {
    return <Object?>[
      entitlements,
      virtualCurrencies,
      productId,
      storeTransactionId,
      isDeferred,
    ];
  }

  static RvPurchaseResult decode(Object result) {
    result as List<Object?>;
    return RvPurchaseResult(
      entitlements: (result[0] as List<Object?>?)!.cast<RvEntitlement>(),
      virtualCurrencies: (result[1] as Map<Object?, Object?>?)!.cast<String, int>(),
      productId: result[2]! as String,
      storeTransactionId: result[3]! as String,
      isDeferred: result[4]! as bool,
    );
  }
}

/// Mirrors the `{ subscriberId, funnelAnswersJson }` shape returned by
/// `claimFunnelToken` / `claimInstall` / `claimFromClipboard` and emitted by
/// the `onFunnelClaimResolved` native event.
class RvFunnelClaim {
  RvFunnelClaim({
    required this.subscriberId,
    required this.funnelAnswersJson,
  });

  String subscriberId;

  String funnelAnswersJson;

  Object encode() {
    return <Object?>[
      subscriberId,
      funnelAnswersJson,
    ];
  }

  static RvFunnelClaim decode(Object result) {
    result as List<Object?>;
    return RvFunnelClaim(
      subscriberId: result[0]! as String,
      funnelAnswersJson: result[1]! as String,
    );
  }
}

/// Mirrors `claimInstall`'s `params` object — all fields optional.
class RvClaimInstallParams {
  RvClaimInstallParams({
    this.platform,
    this.locale,
    this.timezone,
    this.screenDims,
    this.deviceModel,
    this.installReferrer,
  });

  String? platform;

  String? locale;

  String? timezone;

  String? screenDims;

  String? deviceModel;

  String? installReferrer;

  Object encode() {
    return <Object?>[
      platform,
      locale,
      timezone,
      screenDims,
      deviceModel,
      installReferrer,
    ];
  }

  static RvClaimInstallParams decode(Object result) {
    result as List<Object?>;
    return RvClaimInstallParams(
      platform: result[0] as String?,
      locale: result[1] as String?,
      timezone: result[2] as String?,
      screenDims: result[3] as String?,
      deviceModel: result[4] as String?,
      installReferrer: result[5] as String?,
    );
  }
}

/// Mirrors the native `onChange` event payload (`{ event: ChangeEvent }`).
class RvChangeEvent {
  RvChangeEvent({
    required this.kind,
  });

  RvChangeEventKind kind;

  Object encode() {
    return <Object?>[
      kind,
    ];
  }

  static RvChangeEvent decode(Object result) {
    result as List<Object?>;
    return RvChangeEvent(
      kind: result[0]! as RvChangeEventKind,
    );
  }
}

/// Mirrors `LogEntryDTO`.
class RvLogRecord {
  RvLogRecord({
    required this.level,
    required this.message,
    required this.fields,
  });

  RvLogLevel level;

  String message;

  Map<String, String> fields;

  Object encode() {
    return <Object?>[
      level,
      message,
      fields,
    ];
  }

  static RvLogRecord decode(Object result) {
    result as List<Object?>;
    return RvLogRecord(
      level: result[0]! as RvLogLevel,
      message: result[1]! as String,
      fields: (result[2] as Map<Object?, Object?>?)!.cast<String, String>(),
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is RvLogLevel) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is RvProductType) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is RvSessionEventKind) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is RvProductCategory) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is RvPeriodUnit) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    }    else if (value is RvPaymentMode) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    }    else if (value is RvDiscountType) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    }    else if (value is RvRecurrenceMode) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    }    else if (value is RvPackageType) {
      buffer.putUint8(137);
      writeValue(buffer, value.index);
    }    else if (value is RvChangeEventKind) {
      buffer.putUint8(138);
      writeValue(buffer, value.index);
    }    else if (value is RvUser) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is RvEntitlement) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is RvPeriod) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    }    else if (value is RvIntroPrice) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    }    else if (value is RvDiscount) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    }    else if (value is RvPricingPhase) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    }    else if (value is RvSubscriptionOption) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    }    else if (value is RvStoreProduct) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    }    else if (value is RvPackage) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    }    else if (value is RvOffering) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    }    else if (value is RvOfferings) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    }    else if (value is RvPresentedContext) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    }    else if (value is RvPaywall) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    }    else if (value is RvExperimentAssignment) {
      buffer.putUint8(152);
      writeValue(buffer, value.encode());
    }    else if (value is RvPurchaseResult) {
      buffer.putUint8(153);
      writeValue(buffer, value.encode());
    }    else if (value is RvFunnelClaim) {
      buffer.putUint8(154);
      writeValue(buffer, value.encode());
    }    else if (value is RvClaimInstallParams) {
      buffer.putUint8(155);
      writeValue(buffer, value.encode());
    }    else if (value is RvChangeEvent) {
      buffer.putUint8(156);
      writeValue(buffer, value.encode());
    }    else if (value is RvLogRecord) {
      buffer.putUint8(157);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : RvLogLevel.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : RvProductType.values[value];
      case 131: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : RvSessionEventKind.values[value];
      case 132: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : RvProductCategory.values[value];
      case 133: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : RvPeriodUnit.values[value];
      case 134: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : RvPaymentMode.values[value];
      case 135: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : RvDiscountType.values[value];
      case 136: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : RvRecurrenceMode.values[value];
      case 137: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : RvPackageType.values[value];
      case 138: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : RvChangeEventKind.values[value];
      case 139: 
        return RvUser.decode(readValue(buffer)!);
      case 140: 
        return RvEntitlement.decode(readValue(buffer)!);
      case 141: 
        return RvPeriod.decode(readValue(buffer)!);
      case 142: 
        return RvIntroPrice.decode(readValue(buffer)!);
      case 143: 
        return RvDiscount.decode(readValue(buffer)!);
      case 144: 
        return RvPricingPhase.decode(readValue(buffer)!);
      case 145: 
        return RvSubscriptionOption.decode(readValue(buffer)!);
      case 146: 
        return RvStoreProduct.decode(readValue(buffer)!);
      case 147: 
        return RvPackage.decode(readValue(buffer)!);
      case 148: 
        return RvOffering.decode(readValue(buffer)!);
      case 149: 
        return RvOfferings.decode(readValue(buffer)!);
      case 150: 
        return RvPresentedContext.decode(readValue(buffer)!);
      case 151: 
        return RvPaywall.decode(readValue(buffer)!);
      case 152: 
        return RvExperimentAssignment.decode(readValue(buffer)!);
      case 153: 
        return RvPurchaseResult.decode(readValue(buffer)!);
      case 154: 
        return RvFunnelClaim.decode(readValue(buffer)!);
      case 155: 
        return RvClaimInstallParams.decode(readValue(buffer)!);
      case 156: 
        return RvChangeEvent.decode(readValue(buffer)!);
      case 157: 
        return RvLogRecord.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class RovenueHostApi {
  /// Constructor for [RovenueHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  RovenueHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> configure(String apiKey, String? baseUrl, RvLogLevel logLevel, String? appVersion, String? environment) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.configure$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[apiKey, baseUrl, logLevel, appVersion, environment]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> shutdown() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.shutdown$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setForeground(bool foreground) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.setForeground$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[foreground]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<String> getVersion() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.getVersion$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<String?> getAppVersion() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.getAppVersion$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as String?);
    }
  }

  Future<RvUser> currentUser() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.currentUser$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as RvUser?)!;
    }
  }

  Future<void> identify(String appUserId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.identify$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[appUserId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> logOut() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.logOut$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<RvEntitlement?> entitlement(String id) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.entitlement$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[id]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as RvEntitlement?);
    }
  }

  Future<List<RvEntitlement>> entitlementsAll() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.entitlementsAll$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<RvEntitlement>();
    }
  }

  Future<void> refreshEntitlements() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.refreshEntitlements$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<Map<String, int>> virtualCurrencies() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.virtualCurrencies$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as Map<Object?, Object?>?)!.cast<String, int>();
    }
  }

  Future<int> virtualCurrency(String code) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.virtualCurrency$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[code]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as int?)!;
    }
  }

  Future<void> refreshVirtualCurrencies() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.refreshVirtualCurrencies$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<RvOfferings> getOfferings() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.getOfferings$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as RvOfferings?)!;
    }
  }

  Future<RvPaywall?> getPaywall(String placementId, String? locale) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.getPaywall$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[placementId, locale]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as RvPaywall?);
    }
  }

  Future<int> setFallbackPlacements(String json) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.setFallbackPlacements$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[json]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as int?)!;
    }
  }

  Future<RvPurchaseResult> purchase(String productId, RvProductType productType, String? promotionalOfferId, String? basePlanId, String? offerId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.purchase$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[productId, productType, promotionalOfferId, basePlanId, offerId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as RvPurchaseResult?)!;
    }
  }

  Future<RvPurchaseResult> restorePurchases() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.restorePurchases$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as RvPurchaseResult?)!;
    }
  }

  Future<void> refreshRemoteConfig() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.refreshRemoteConfig$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<bool> remoteConfigBool(String key, bool fallback) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.remoteConfigBool$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[key, fallback]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<String> remoteConfigString(String key, String fallback) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.remoteConfigString$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[key, fallback]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<int> remoteConfigInt(String key, int fallback) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.remoteConfigInt$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[key, fallback]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as int?)!;
    }
  }

  Future<double> remoteConfigDouble(String key, double fallback) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.remoteConfigDouble$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[key, fallback]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as double?)!;
    }
  }

  Future<String?> remoteConfigJson(String key) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.remoteConfigJson$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[key]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as String?);
    }
  }

  Future<List<String>> remoteConfigKeys() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.remoteConfigKeys$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<String>();
    }
  }

  Future<String> remoteConfigAllJson() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.remoteConfigAllJson$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<RvExperimentAssignment?> experiment(String key) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.experiment$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[key]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as RvExperimentAssignment?);
    }
  }

  Future<List<RvExperimentAssignment>> experimentsAll() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.experimentsAll$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<RvExperimentAssignment>();
    }
  }

  Future<String> getAppAccountToken() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.getAppAccountToken$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<void> recordSessionEvent(RvSessionEventKind kind, String occurredAt, int? durationMs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.recordSessionEvent$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[kind, occurredAt, durationMs]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<int> flushSessionEvents() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.flushSessionEvents$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as int?)!;
    }
  }

  Future<RvFunnelClaim> claimFunnelToken(String token) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.claimFunnelToken$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[token]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as RvFunnelClaim?)!;
    }
  }

  Future<RvFunnelClaim?> claimInstall(RvClaimInstallParams params) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.claimInstall$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[params]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as RvFunnelClaim?);
    }
  }

  Future<void> claimViaEmail(String email) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.claimViaEmail$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[email]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<RvFunnelClaim?> claimFromClipboard() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.claimFromClipboard$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as RvFunnelClaim?);
    }
  }

  Future<String> installId() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.installId$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<bool> hasResolvedFunnelClaim() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.hasResolvedFunnelClaim$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<void> track(String envelopeJson) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.track$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[envelopeJson]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> enqueuePaywallEvent(String envelopeJson) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.enqueuePaywallEvent$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[envelopeJson]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setAttributes(Map<String, String?> attributes) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.setAttributes$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[attributes]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setEmail(String? email) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.setEmail$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[email]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setDisplayName(String? name) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.setDisplayName$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[name]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setPhoneNumber(String? phone) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.setPhoneNumber$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[phone]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setPushToken(String? token) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.setPushToken$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[token]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<int> flushAttributes() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.flushAttributes$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as int?)!;
    }
  }
}

abstract class RovenueFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onChange(RvChangeEvent event);

  void onLog(RvLogRecord record);

  void onFunnelClaim(RvFunnelClaim claim);

  static void setUp(RovenueFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueFlutterApi.onChange$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueFlutterApi.onChange was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final RvChangeEvent? arg_event = (args[0] as RvChangeEvent?);
          assert(arg_event != null,
              'Argument for dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueFlutterApi.onChange was null, expected non-null RvChangeEvent.');
          try {
            api.onChange(arg_event!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueFlutterApi.onLog$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueFlutterApi.onLog was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final RvLogRecord? arg_record = (args[0] as RvLogRecord?);
          assert(arg_record != null,
              'Argument for dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueFlutterApi.onLog was null, expected non-null RvLogRecord.');
          try {
            api.onLog(arg_record!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueFlutterApi.onFunnelClaim$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueFlutterApi.onFunnelClaim was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final RvFunnelClaim? arg_claim = (args[0] as RvFunnelClaim?);
          assert(arg_claim != null,
              'Argument for dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueFlutterApi.onFunnelClaim was null, expected non-null RvFunnelClaim.');
          try {
            api.onFunnelClaim(arg_claim!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
