import type { CountryCode, Subscriber, TimelineEntry } from "./types";

type CountryMeta = { name: string; flag: string };

/**
 * Country metadata used by the country cell + detail panel. The `flag`
 * value is intentionally a CSS background — gradients keep the prototype
 * dependency-free at the cost of pixel-perfect accuracy.
 */
export const COUNTRIES: Readonly<Record<CountryCode, CountryMeta>> = {
  US: {
    name: "United States",
    flag: "linear-gradient(to bottom, #B22234 33%, #fff 33% 66%, #B22234 66%)",
  },
  DE: {
    name: "Germany",
    flag: "linear-gradient(to bottom, #000 33%, #DD0000 33% 66%, #FFCE00 66%)",
  },
  TR: { name: "Türkiye", flag: "#E30A17" },
  JP: { name: "Japan", flag: "#fff" },
  BR: { name: "Brazil", flag: "#009C3B" },
  GB: { name: "United Kingdom", flag: "linear-gradient(135deg, #012169, #C8102E)" },
  FR: {
    name: "France",
    flag: "linear-gradient(to right, #002654 33%, #fff 33% 66%, #ED2939 66%)",
  },
  IN: {
    name: "India",
    flag: "linear-gradient(to bottom, #FF9933 33%, #fff 33% 66%, #138808 66%)",
  },
  CA: { name: "Canada", flag: "#FF0000" },
  AU: { name: "Australia", flag: "#012169" },
  NL: {
    name: "Netherlands",
    flag: "linear-gradient(to bottom, #AE1C28 33%, #fff 33% 66%, #21468B 66%)",
  },
  KR: { name: "South Korea", flag: "#fff" },
};

/**
 * Avatar gradients, picked deterministically by hashing a slice of the user
 * id so the same user always gets the same color across renders.
 */
export const AVATAR_GRADIENTS: ReadonlyArray<string> = [
  "linear-gradient(135deg, #3B82F6, #1D4ED8)",
  "linear-gradient(135deg, #8B5CF6, #6D28D9)",
  "linear-gradient(135deg, #10B981, #047857)",
  "linear-gradient(135deg, #F59E0B, #B45309)",
  "linear-gradient(135deg, #EC4899, #BE123B)",
  "linear-gradient(135deg, #06B6D4, #0E7490)",
  "linear-gradient(135deg, #F97316, #C2410C)",
  "linear-gradient(135deg, #84CC16, #4D7C0F)",
];

export const SUBSCRIBERS: ReadonlyArray<Subscriber> = (
  [
  {
    id: "user_9f2a7b...",
    full: "user_9f2a7b31e8",
    alias: "emma.w@—",
    country: "US",
    access: ["premium", "unlimited_exports"],
    product: "premium_yearly",
    status: "active",
    ltv: 284.5,
    mrr: 6.66,
    created: "Feb 12, 2026",
    renew: "Feb 12, 2027",
    platforms: ["ios"],
    risk: 8,
    vip: true,
    plan: "Premium",
  },
  {
    id: "user_b81c4d...",
    full: "user_b81c4d2f07",
    alias: "rkr.dev@—",
    country: "DE",
    access: ["pro"],
    product: "pro_monthly",
    status: "active",
    ltv: 54.89,
    mrr: 4.99,
    created: "Jan 03, 2026",
    renew: "Apr 24, 2026",
    platforms: ["android"],
    risk: 22,
    plan: "Pro",
  },
  {
    id: "user_4d0e11...",
    full: "user_4d0e118a22",
    alias: "mert.k@—",
    country: "TR",
    access: ["premium"],
    product: "premium_monthly",
    status: "trial",
    ltv: 0,
    mrr: 0,
    created: "Apr 18, 2026",
    renew: "Apr 22, 2026",
    platforms: ["ios"],
    risk: 64,
    plan: "Trial",
  },
  {
    id: "user_7c9e22...",
    full: "user_7c9e226fa1",
    alias: "noah.s@—",
    country: "GB",
    access: ["premium", "unlimited_exports"],
    product: "premium_yearly",
    status: "active",
    ltv: 479.94,
    mrr: 6.66,
    created: "Apr 20, 2025",
    renew: "Apr 20, 2026",
    platforms: ["ios", "web"],
    risk: 81,
    plan: "Premium",
    renewsIn: "3d",
  },
  {
    id: "user_2a8f0c...",
    full: "user_2a8f0c19bb",
    alias: "ayaka.t@—",
    country: "JP",
    access: ["premium", "unlimited_exports", "lifetime_badge"],
    product: "lifetime_unlock",
    status: "active",
    ltv: 149.0,
    mrr: 0,
    created: "Mar 01, 2026",
    renew: "—",
    platforms: ["ios"],
    risk: 3,
    vip: true,
    plan: "Lifetime",
  },
  {
    id: "user_5b6c1f...",
    full: "user_5b6c1f7ad3",
    alias: "lucas.b@—",
    country: "BR",
    access: [],
    product: "premium_monthly",
    status: "churned",
    ltv: 29.97,
    mrr: 0,
    created: "Oct 14, 2025",
    renew: "Feb 14, 2026",
    platforms: ["android"],
    risk: 100,
    plan: "—",
  },
  {
    id: "user_e4f3aa...",
    full: "user_e4f3aa819c",
    alias: "chloe.m@—",
    country: "FR",
    access: ["pro"],
    product: "pro_yearly",
    status: "active",
    ltv: 79.98,
    mrr: 3.33,
    created: "Nov 22, 2024",
    renew: "Nov 22, 2026",
    platforms: ["ios"],
    risk: 12,
    plan: "Pro",
  },
  {
    id: "user_ff0b8d...",
    full: "user_ff0b8d3e44",
    alias: "arjun.p@—",
    country: "IN",
    access: ["basic"],
    product: "starter_monthly",
    status: "active",
    ltv: 11.94,
    mrr: 1.99,
    created: "Jan 29, 2026",
    renew: "May 02, 2026",
    platforms: ["android"],
    risk: 31,
    plan: "Starter",
  },
  {
    id: "user_1c55ee...",
    full: "user_1c55ee8a0b",
    alias: "ivy.r@—",
    country: "CA",
    access: ["premium", "unlimited_exports"],
    product: "premium_monthly",
    status: "grace",
    ltv: 89.91,
    mrr: 0,
    created: "Aug 07, 2025",
    renew: "Apr 17, 2026",
    platforms: ["ios"],
    risk: 88,
    plan: "Premium",
    billingIssue: true,
  },
  {
    id: "user_88a01d...",
    full: "user_88a01d7eef",
    alias: "zoe.g@—",
    country: "AU",
    access: ["premium"],
    product: "premium_weekly",
    status: "trial",
    ltv: 0,
    mrr: 0,
    created: "Apr 17, 2026",
    renew: "Apr 21, 2026",
    platforms: ["android"],
    risk: 51,
    plan: "Trial",
  },
  {
    id: "user_0fe92c...",
    full: "user_0fe92c4d72",
    alias: "sven.h@—",
    country: "NL",
    access: ["premium", "unlimited_exports"],
    product: "premium_yearly",
    status: "active",
    ltv: 159.98,
    mrr: 6.66,
    created: "Feb 09, 2025",
    renew: "Feb 09, 2027",
    platforms: ["ios", "android"],
    risk: 7,
    vip: true,
    plan: "Premium",
  },
  {
    id: "user_33b7ca...",
    full: "user_33b7ca90ff",
    alias: "jihoon.k@—",
    country: "KR",
    access: ["pro"],
    product: "pro_monthly",
    status: "active",
    ltv: 34.93,
    mrr: 4.99,
    created: "Dec 11, 2025",
    renew: "Apr 23, 2026",
    platforms: ["ios"],
    risk: 18,
    plan: "Pro",
  },
  {
    id: "user_a12bff...",
    full: "user_a12bff5521",
    alias: "oliver.d@—",
    country: "US",
    access: [],
    product: "pro_monthly",
    status: "canceled",
    ltv: 19.96,
    mrr: 0,
    created: "Dec 02, 2025",
    renew: "Mar 02, 2026",
    platforms: ["android"],
    risk: 100,
    plan: "—",
  },
  {
    id: "user_beef91...",
    full: "user_beef912cc8",
    alias: "sofia.l@—",
    country: "BR",
    access: ["premium"],
    product: "premium_monthly",
    status: "active",
    ltv: 19.98,
    mrr: 9.99,
    created: "Mar 14, 2026",
    renew: "Apr 28, 2026",
    platforms: ["ios"],
    risk: 42,
    plan: "Premium",
  },
] satisfies ReadonlyArray<Omit<Subscriber, "rovenueId" | "name">>).map((s) => ({
  ...s,
  // Mock fixtures have no real internal id; derive a stable stand-in.
  rovenueId: s.full,
  // Derive a readable display name from the masked alias (e.g. "emma.w@—" → "Emma W").
  name: s.alias
    .split("@")[0]!
    .split(".")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" "),
}));

export const TIMELINE_MOCK: ReadonlyArray<TimelineEntry> = [
  {
    kind: "purchase",
    typeKey: "initial_purchase",
    at: "2s ago",
    product: "premium_yearly",
    amount: "$79.99",
  },
  {
    kind: "renewal",
    typeKey: "subscription_renewed",
    at: "3d ago",
    product: "premium_yearly",
    amount: "$79.99",
  },
  {
    kind: "trial",
    typeKey: "trial_converted",
    at: "Feb 19",
    product: "premium_yearly",
    amount: "$79.99",
  },
  {
    kind: "trial",
    typeKey: "trial_started",
    at: "Feb 12",
    product: "premium_yearly",
    amount: "—",
  },
  {
    kind: "purchase",
    typeKey: "session_paywall_v2",
    at: "Feb 12",
    product: "onboarding",
    amount: "—",
  },
  {
    kind: "fail",
    typeKey: "billing_issue_retry",
    at: "Jan 15",
    product: "premium_yearly",
    amount: "—",
  },
];
