import type {
  BillingIssue,
  CalendarDay,
  CohortRow,
  CompositionSegment,
  Subscription,
} from "./types";

export const SUBSCRIPTIONS: ReadonlyArray<Subscription> = [
  {
    id: "sub_01HX9K2",
    user: "user_9f2a7b",
    product: "premium_yearly",
    status: "active",
    store: "ios",
    price: 79.99,
    started: "2026-02-12",
    renewsIn: 297,
    renewsPct: 82,
    autoRenew: true,
    billingCycle: "yearly",
    cancelPolicy: "none",
    intro: false,
    term: "12 mo",
    trialDays: 7,
    entitlements: ["premium", "unlimited_exports"],
  },
  {
    id: "sub_01HX2Q8",
    user: "user_b81c4d",
    product: "pro_monthly",
    status: "active",
    store: "play",
    price: 4.99,
    started: "2026-01-03",
    renewsIn: 4,
    renewsPct: 13,
    autoRenew: true,
    billingCycle: "monthly",
    cancelPolicy: "none",
    intro: false,
    term: "30d",
    trialDays: 0,
    entitlements: ["pro"],
  },
  {
    id: "sub_01HX4R1",
    user: "user_4d0e11",
    product: "premium_monthly",
    status: "trial",
    store: "ios",
    price: 9.99,
    started: "2026-04-18",
    renewsIn: 2,
    renewsPct: 40,
    autoRenew: true,
    billingCycle: "monthly",
    cancelPolicy: "none",
    intro: true,
    term: "7d trial",
    trialDays: 7,
    entitlements: ["premium"],
  },
  {
    id: "sub_01HWM0A",
    user: "user_7c9e22",
    product: "premium_yearly",
    status: "active",
    store: "stripe",
    price: 79.99,
    started: "2025-04-20",
    renewsIn: 3,
    renewsPct: 99,
    autoRenew: true,
    billingCycle: "yearly",
    cancelPolicy: "none",
    intro: false,
    term: "12 mo",
    trialDays: 0,
    entitlements: ["premium", "unlimited_exports"],
    lastIssue: "retry succeeded 2d ago",
  },
  {
    id: "sub_01HV4M9",
    user: "user_1c55ee",
    product: "premium_monthly",
    status: "grace",
    store: "ios",
    price: 9.99,
    started: "2025-08-07",
    renewsIn: 0,
    renewsPct: 100,
    autoRenew: true,
    billingCycle: "monthly",
    cancelPolicy: "billing_retry",
    intro: false,
    term: "in retry",
    trialDays: 0,
    entitlements: ["premium"],
    lastIssue: "card declined · 2 attempts",
  },
  {
    id: "sub_01HX7P3",
    user: "user_0fe92c",
    product: "premium_yearly",
    status: "active",
    store: "ios",
    price: 79.99,
    started: "2025-02-09",
    renewsIn: 295,
    renewsPct: 81,
    autoRenew: true,
    billingCycle: "yearly",
    cancelPolicy: "none",
    intro: false,
    term: "12 mo",
    trialDays: 0,
    entitlements: ["premium", "unlimited_exports"],
  },
  {
    id: "sub_01HW7V5",
    user: "user_a12bff",
    product: "pro_monthly",
    status: "canceling",
    store: "play",
    price: 4.99,
    started: "2025-12-02",
    renewsIn: 12,
    renewsPct: 60,
    autoRenew: false,
    billingCycle: "monthly",
    cancelPolicy: "user_canceled",
    intro: false,
    term: "ends Apr 02",
    trialDays: 0,
    entitlements: ["pro"],
    cancelReason: "too_expensive",
  },
  {
    id: "sub_01HX1C8",
    user: "user_ff0b8d",
    product: "starter_monthly",
    status: "active",
    store: "play",
    price: 1.99,
    started: "2026-01-29",
    renewsIn: 12,
    renewsPct: 60,
    autoRenew: true,
    billingCycle: "monthly",
    cancelPolicy: "none",
    intro: false,
    term: "30d",
    trialDays: 0,
    entitlements: ["basic"],
  },
  {
    id: "sub_01HV9Z2",
    user: "user_5b6c1f",
    product: "premium_monthly",
    status: "churned",
    store: "play",
    price: 9.99,
    started: "2025-10-14",
    renewsIn: -63,
    renewsPct: 100,
    autoRenew: false,
    billingCycle: "monthly",
    cancelPolicy: "grace_expired",
    intro: false,
    term: "ended Feb 14",
    trialDays: 0,
    entitlements: [],
  },
  {
    id: "sub_01HX3F0",
    user: "user_88a01d",
    product: "premium_weekly",
    status: "trial",
    store: "play",
    price: 2.99,
    started: "2026-04-17",
    renewsIn: 1,
    renewsPct: 80,
    autoRenew: true,
    billingCycle: "weekly",
    cancelPolicy: "none",
    intro: true,
    term: "3d trial",
    trialDays: 3,
    entitlements: ["premium"],
  },
  {
    id: "sub_01HV0LK",
    user: "user_e4f3aa",
    product: "pro_yearly",
    status: "active",
    store: "ios",
    price: 39.99,
    started: "2024-11-22",
    renewsIn: 216,
    renewsPct: 70,
    autoRenew: true,
    billingCycle: "yearly",
    cancelPolicy: "none",
    intro: false,
    term: "12 mo",
    trialDays: 0,
    entitlements: ["pro"],
  },
  {
    id: "sub_01HX2LD",
    user: "user_33b7ca",
    product: "pro_monthly",
    status: "active",
    store: "ios",
    price: 4.99,
    started: "2025-12-11",
    renewsIn: 3,
    renewsPct: 10,
    autoRenew: true,
    billingCycle: "monthly",
    cancelPolicy: "none",
    intro: false,
    term: "30d",
    trialDays: 0,
    entitlements: ["pro"],
    lastIssue: "billing retry scheduled",
  },
];

/**
 * 28-day window centered six days behind "today". Past slots only carry
 * `failed` counts; future slots track upcoming renewals + their breakdown.
 * Values are deterministic so the layout snapshot stays stable.
 */
export const CALENDAR_DAYS: ReadonlyArray<CalendarDay> = [
  { day: -6, today: false, past: true, renewals: 0, trials: 0, grace: 0, failed: 4 },
  { day: -5, today: false, past: true, renewals: 0, trials: 0, grace: 0, failed: 3 },
  { day: -4, today: false, past: true, renewals: 0, trials: 0, grace: 0, failed: 5 },
  { day: -3, today: false, past: true, renewals: 0, trials: 0, grace: 0, failed: 2 },
  { day: -2, today: false, past: true, renewals: 0, trials: 0, grace: 0, failed: 4 },
  { day: -1, today: false, past: true, renewals: 0, trials: 0, grace: 0, failed: 3 },
  { day: 0,  today: true,  past: false, renewals: 14, trials: 4, grace: 1, failed: 0 },
  { day: 1,  today: false, past: false, renewals: 11, trials: 3, grace: 0, failed: 0 },
  { day: 2,  today: false, past: false, renewals: 13, trials: 5, grace: 1, failed: 0 },
  { day: 3,  today: false, past: false, renewals: 28, trials: 6, grace: 2, failed: 0 },
  { day: 4,  today: false, past: false, renewals: 16, trials: 4, grace: 0, failed: 0 },
  { day: 5,  today: false, past: false, renewals: 12, trials: 2, grace: 1, failed: 0 },
  { day: 6,  today: false, past: false, renewals: 17, trials: 3, grace: 1, failed: 0 },
  { day: 7,  today: false, past: false, renewals: 22, trials: 6, grace: 2, failed: 0 },
  { day: 8,  today: false, past: false, renewals: 14, trials: 4, grace: 0, failed: 0 },
  { day: 9,  today: false, past: false, renewals: 12, trials: 3, grace: 1, failed: 0 },
  { day: 10, today: false, past: false, renewals: 10, trials: 2, grace: 0, failed: 0 },
  { day: 11, today: false, past: false, renewals: 11, trials: 4, grace: 1, failed: 0 },
  { day: 12, today: false, past: false, renewals: 13, trials: 5, grace: 2, failed: 0 },
  { day: 13, today: false, past: false, renewals: 9,  trials: 3, grace: 0, failed: 0 },
  { day: 14, today: false, past: false, renewals: 12, trials: 4, grace: 1, failed: 0 },
  { day: 15, today: false, past: false, renewals: 18, trials: 6, grace: 1, failed: 0 },
  { day: 16, today: false, past: false, renewals: 15, trials: 3, grace: 0, failed: 0 },
  { day: 17, today: false, past: false, renewals: 11, trials: 2, grace: 1, failed: 0 },
  { day: 18, today: false, past: false, renewals: 13, trials: 4, grace: 0, failed: 0 },
  { day: 19, today: false, past: false, renewals: 10, trials: 3, grace: 0, failed: 0 },
  { day: 20, today: false, past: false, renewals: 14, trials: 5, grace: 2, failed: 0 },
  { day: 21, today: false, past: false, renewals: 16, trials: 4, grace: 1, failed: 0 },
];

/** Headcount + share for the composition bar on the page header. */
export const COMPOSITION_SEGMENTS: ReadonlyArray<CompositionSegment> = [
  { key: "active",    count: 19204, share: "90.9%", color: "var(--color-rv-accent-500)" },
  { key: "trial",     count: 1421,  share: "6.7%",  color: "var(--color-rv-success)" },
  { key: "canceling", count: 312,   share: "1.5%",  color: "var(--color-rv-warning)" },
  { key: "grace",     count: 84,    share: "0.4%",  color: "var(--color-rv-danger)" },
  { key: "paused",    count: 96,    share: "0.5%",  color: "var(--color-rv-mute-400)" },
];

export const COMPOSITION_TOTAL = COMPOSITION_SEGMENTS.reduce(
  (sum, seg) => sum + seg.count,
  0,
);

export const BILLING_ISSUES: ReadonlyArray<BillingIssue> = [
  { user: "user_1c55ee", id: "sub_01HV4M9", issue: "Card declined",          product: "premium_monthly", attempts: 2, next: "retry in 6h",     severity: "high",     mrr: 9.99 },
  { user: "user_33b7ca", id: "sub_01HX2LD", issue: "Insufficient funds",     product: "pro_monthly",     attempts: 1, next: "retry in 24h",    severity: "high",     mrr: 4.99 },
  { user: "user_4b10ff", id: "sub_01HW8AA", issue: "Expired payment method", product: "premium_yearly",  attempts: 3, next: "grace ends 3d",   severity: "medium",   mrr: 6.66 },
  { user: "user_c12ade", id: "sub_01HV9MM", issue: "Store price mismatch",   product: "pro_yearly",      attempts: 0, next: "manual review",   severity: "low",      mrr: 3.33 },
  { user: "user_7c9e22", id: "sub_01HWM0A", issue: "Card declined",          product: "premium_yearly",  attempts: 1, next: "resolved 2d ago", severity: "resolved", mrr: 6.66 },
];

export const COHORT_MATRIX: ReadonlyArray<CohortRow> = [
  { label: "Nov 2025", values: [100, 82, 71, 65, 61, 58] },
  { label: "Dec 2025", values: [100, 84, 73, 67, 62, null] },
  { label: "Jan 2026", values: [100, 86, 76, 70, null, null] },
  { label: "Feb 2026", values: [100, 88, 79, null, null, null] },
  { label: "Mar 2026", values: [100, 89, null, null, null, null] },
  { label: "Apr 2026", values: [100, null, null, null, null, null] },
];

export const COHORT_HEADERS = ["M0", "M1", "M2", "M3", "M4", "M5"] as const;

export const SCOPE_COUNTS = {
  all: "21.1k",
  active: "19.2k",
  trial: "1,421",
  grace: "84",
  canceling: "312",
  issues: "127",
  churned: "2.0k",
} as const;
