// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Mirrors the `"off" | "error" | "warn" | "info" | "debug" | "trace"`
/// log-level union used by `configure()` and `LogEntryDTO.level`.
enum RvLogLevel: Int {
  case off = 0
  case error = 1
  case warn = 2
  case info = 3
  case debug = 4
  case trace = 5
}

/// Mirrors `ProductTypeDTO` (`"subscription" | "consumable" |
/// "non_consumable"`).
enum RvProductType: Int {
  case subscription = 0
  case consumable = 1
  case nonConsumable = 2
}

/// Mirrors the `"open" | "background" | "close"` union accepted by
/// `recordSessionEvent`.
enum RvSessionEventKind: Int {
  case open = 0
  case background = 1
  case close = 2
}

/// Mirrors `ProductCategoryDTO`.
enum RvProductCategory: Int {
  case subscription = 0
  case nonSubscription = 1
}

/// Mirrors `PeriodUnitDTO`.
enum RvPeriodUnit: Int {
  case day = 0
  case week = 1
  case month = 2
  case year = 3
}

/// Mirrors `PaymentModeDTO`.
enum RvPaymentMode: Int {
  case freeTrial = 0
  case payAsYouGo = 1
  case payUpFront = 2
}

/// Mirrors `DiscountTypeDTO`.
enum RvDiscountType: Int {
  case introductory = 0
  case promotional = 1
  case winBack = 2
}

/// Mirrors `RecurrenceModeDTO`.
enum RvRecurrenceMode: Int {
  case infiniteRecurring = 0
  case finiteRecurring = 1
  case nonRecurring = 2
}

/// Mirrors `PackageTypeDTO`.
enum RvPackageType: Int {
  case unknown = 0
  case custom = 1
  case lifetime = 2
  case annual = 3
  case sixMonth = 4
  case threeMonth = 5
  case twoMonth = 6
  case monthly = 7
  case weekly = 8
}

/// Mirrors `ChangeEvent` (`packages/sdk-rn/src/types.ts`) — the native
/// `onChange` event payload's `event` discriminant.
enum RvChangeEventKind: Int {
  case entitlementsChanged = 0
  case identityChanged = 1
  case virtualCurrenciesChanged = 2
  case remoteConfigChanged = 3
}

/// Generated class from Pigeon that represents data sent in messages.
struct RvUser {
  var rovenueId: String
  var appUserId: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RvUser? {
    let rovenueId = pigeonVar_list[0] as! String
    let appUserId: String? = nilOrValue(pigeonVar_list[1])

    return RvUser(
      rovenueId: rovenueId,
      appUserId: appUserId
    )
  }
  func toList() -> [Any?] {
    return [
      rovenueId,
      appUserId,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RvEntitlement {
  var id: String
  var active: Bool
  var expiresAt: String? = nil
  var productId: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RvEntitlement? {
    let id = pigeonVar_list[0] as! String
    let active = pigeonVar_list[1] as! Bool
    let expiresAt: String? = nilOrValue(pigeonVar_list[2])
    let productId: String? = nilOrValue(pigeonVar_list[3])

    return RvEntitlement(
      id: id,
      active: active,
      expiresAt: expiresAt,
      productId: productId
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      active,
      expiresAt,
      productId,
    ]
  }
}

/// Mirrors `PeriodDTO`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RvPeriod {
  var value: Int64
  var unit: RvPeriodUnit
  var iso8601: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RvPeriod? {
    let value = pigeonVar_list[0] as! Int64
    let unit = pigeonVar_list[1] as! RvPeriodUnit
    let iso8601 = pigeonVar_list[2] as! String

    return RvPeriod(
      value: value,
      unit: unit,
      iso8601: iso8601
    )
  }
  func toList() -> [Any?] {
    return [
      value,
      unit,
      iso8601,
    ]
  }
}

/// Mirrors `IntroPriceDTO`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RvIntroPrice {
  var price: Double? = nil
  var priceString: String? = nil
  var currencyCode: String? = nil
  var period: RvPeriod
  var cycles: Int64
  var paymentMode: RvPaymentMode


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RvIntroPrice? {
    let price: Double? = nilOrValue(pigeonVar_list[0])
    let priceString: String? = nilOrValue(pigeonVar_list[1])
    let currencyCode: String? = nilOrValue(pigeonVar_list[2])
    let period = pigeonVar_list[3] as! RvPeriod
    let cycles = pigeonVar_list[4] as! Int64
    let paymentMode = pigeonVar_list[5] as! RvPaymentMode

    return RvIntroPrice(
      price: price,
      priceString: priceString,
      currencyCode: currencyCode,
      period: period,
      cycles: cycles,
      paymentMode: paymentMode
    )
  }
  func toList() -> [Any?] {
    return [
      price,
      priceString,
      currencyCode,
      period,
      cycles,
      paymentMode,
    ]
  }
}

/// Mirrors `DiscountDTO`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RvDiscount {
  var identifier: String? = nil
  var price: Double? = nil
  var priceString: String? = nil
  var currencyCode: String? = nil
  var period: RvPeriod
  var numberOfPeriods: Int64
  var paymentMode: RvPaymentMode
  var type: RvDiscountType


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RvDiscount? {
    let identifier: String? = nilOrValue(pigeonVar_list[0])
    let price: Double? = nilOrValue(pigeonVar_list[1])
    let priceString: String? = nilOrValue(pigeonVar_list[2])
    let currencyCode: String? = nilOrValue(pigeonVar_list[3])
    let period = pigeonVar_list[4] as! RvPeriod
    let numberOfPeriods = pigeonVar_list[5] as! Int64
    let paymentMode = pigeonVar_list[6] as! RvPaymentMode
    let type = pigeonVar_list[7] as! RvDiscountType

    return RvDiscount(
      identifier: identifier,
      price: price,
      priceString: priceString,
      currencyCode: currencyCode,
      period: period,
      numberOfPeriods: numberOfPeriods,
      paymentMode: paymentMode,
      type: type
    )
  }
  func toList() -> [Any?] {
    return [
      identifier,
      price,
      priceString,
      currencyCode,
      period,
      numberOfPeriods,
      paymentMode,
      type,
    ]
  }
}

/// Mirrors `PricingPhaseDTO`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RvPricingPhase {
  var price: Double? = nil
  var priceString: String? = nil
  var currencyCode: String? = nil
  var billingPeriod: RvPeriod
  var billingCycleCount: Int64? = nil
  var recurrenceMode: RvRecurrenceMode
  var paymentMode: RvPaymentMode? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RvPricingPhase? {
    let price: Double? = nilOrValue(pigeonVar_list[0])
    let priceString: String? = nilOrValue(pigeonVar_list[1])
    let currencyCode: String? = nilOrValue(pigeonVar_list[2])
    let billingPeriod = pigeonVar_list[3] as! RvPeriod
    let billingCycleCount: Int64? = nilOrValue(pigeonVar_list[4])
    let recurrenceMode = pigeonVar_list[5] as! RvRecurrenceMode
    let paymentMode: RvPaymentMode? = nilOrValue(pigeonVar_list[6])

    return RvPricingPhase(
      price: price,
      priceString: priceString,
      currencyCode: currencyCode,
      billingPeriod: billingPeriod,
      billingCycleCount: billingCycleCount,
      recurrenceMode: recurrenceMode,
      paymentMode: paymentMode
    )
  }
  func toList() -> [Any?] {
    return [
      price,
      priceString,
      currencyCode,
      billingPeriod,
      billingCycleCount,
      recurrenceMode,
      paymentMode,
    ]
  }
}

/// Mirrors `SubscriptionOptionDTO`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RvSubscriptionOption {
  var id: String
  var basePlanId: String? = nil
  var offerId: String? = nil
  var tags: [String]
  var isBasePlan: Bool
  var isPrepaid: Bool
  var pricingPhases: [RvPricingPhase]
  var freePhase: RvPricingPhase? = nil
  var introPhase: RvPricingPhase? = nil
  var fullPricePhase: RvPricingPhase? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RvSubscriptionOption? {
    let id = pigeonVar_list[0] as! String
    let basePlanId: String? = nilOrValue(pigeonVar_list[1])
    let offerId: String? = nilOrValue(pigeonVar_list[2])
    let tags = pigeonVar_list[3] as! [String]
    let isBasePlan = pigeonVar_list[4] as! Bool
    let isPrepaid = pigeonVar_list[5] as! Bool
    let pricingPhases = pigeonVar_list[6] as! [RvPricingPhase]
    let freePhase: RvPricingPhase? = nilOrValue(pigeonVar_list[7])
    let introPhase: RvPricingPhase? = nilOrValue(pigeonVar_list[8])
    let fullPricePhase: RvPricingPhase? = nilOrValue(pigeonVar_list[9])

    return RvSubscriptionOption(
      id: id,
      basePlanId: basePlanId,
      offerId: offerId,
      tags: tags,
      isBasePlan: isBasePlan,
      isPrepaid: isPrepaid,
      pricingPhases: pricingPhases,
      freePhase: freePhase,
      introPhase: introPhase,
      fullPricePhase: fullPricePhase
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      basePlanId,
      offerId,
      tags,
      isBasePlan,
      isPrepaid,
      pricingPhases,
      freePhase,
      introPhase,
      fullPricePhase,
    ]
  }
}

/// Mirrors `StoreProductDTO`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RvStoreProduct {
  var id: String
  var type: RvProductType
  var productCategory: RvProductCategory
  var displayName: String
  var description: String? = nil
  var priceString: String? = nil
  var price: Double? = nil
  var currencyCode: String? = nil
  var subscriptionPeriod: RvPeriod? = nil
  var subscriptionGroupIdentifier: String? = nil
  var isFamilyShareable: Bool
  var introPrice: RvIntroPrice? = nil
  var discounts: [RvDiscount]
  var isEligibleForIntroOffer: Bool? = nil
  var subscriptionOptions: [RvSubscriptionOption]? = nil
  var defaultOption: RvSubscriptionOption? = nil
  var pricePerWeek: Double? = nil
  var pricePerMonth: Double? = nil
  var pricePerYear: Double? = nil
  var pricePerWeekString: String? = nil
  var pricePerMonthString: String? = nil
  var pricePerYearString: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RvStoreProduct? {
    let id = pigeonVar_list[0] as! String
    let type = pigeonVar_list[1] as! RvProductType
    let productCategory = pigeonVar_list[2] as! RvProductCategory
    let displayName = pigeonVar_list[3] as! String
    let description: String? = nilOrValue(pigeonVar_list[4])
    let priceString: String? = nilOrValue(pigeonVar_list[5])
    let price: Double? = nilOrValue(pigeonVar_list[6])
    let currencyCode: String? = nilOrValue(pigeonVar_list[7])
    let subscriptionPeriod: RvPeriod? = nilOrValue(pigeonVar_list[8])
    let subscriptionGroupIdentifier: String? = nilOrValue(pigeonVar_list[9])
    let isFamilyShareable = pigeonVar_list[10] as! Bool
    let introPrice: RvIntroPrice? = nilOrValue(pigeonVar_list[11])
    let discounts = pigeonVar_list[12] as! [RvDiscount]
    let isEligibleForIntroOffer: Bool? = nilOrValue(pigeonVar_list[13])
    let subscriptionOptions: [RvSubscriptionOption]? = nilOrValue(pigeonVar_list[14])
    let defaultOption: RvSubscriptionOption? = nilOrValue(pigeonVar_list[15])
    let pricePerWeek: Double? = nilOrValue(pigeonVar_list[16])
    let pricePerMonth: Double? = nilOrValue(pigeonVar_list[17])
    let pricePerYear: Double? = nilOrValue(pigeonVar_list[18])
    let pricePerWeekString: String? = nilOrValue(pigeonVar_list[19])
    let pricePerMonthString: String? = nilOrValue(pigeonVar_list[20])
    let pricePerYearString: String? = nilOrValue(pigeonVar_list[21])

    return RvStoreProduct(
      id: id,
      type: type,
      productCategory: productCategory,
      displayName: displayName,
      description: description,
      priceString: priceString,
      price: price,
      currencyCode: currencyCode,
      subscriptionPeriod: subscriptionPeriod,
      subscriptionGroupIdentifier: subscriptionGroupIdentifier,
      isFamilyShareable: isFamilyShareable,
      introPrice: introPrice,
      discounts: discounts,
      isEligibleForIntroOffer: isEligibleForIntroOffer,
      subscriptionOptions: subscriptionOptions,
      defaultOption: defaultOption,
      pricePerWeek: pricePerWeek,
      pricePerMonth: pricePerMonth,
      pricePerYear: pricePerYear,
      pricePerWeekString: pricePerWeekString,
      pricePerMonthString: pricePerMonthString,
      pricePerYearString: pricePerYearString
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      type,
      productCategory,
      displayName,
      description,
      priceString,
      price,
      currencyCode,
      subscriptionPeriod,
      subscriptionGroupIdentifier,
      isFamilyShareable,
      introPrice,
      discounts,
      isEligibleForIntroOffer,
      subscriptionOptions,
      defaultOption,
      pricePerWeek,
      pricePerMonth,
      pricePerYear,
      pricePerWeekString,
      pricePerMonthString,
      pricePerYearString,
    ]
  }
}

/// Mirrors `PackageDTO`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RvPackage {
  var identifier: String
  var packageType: RvPackageType? = nil
  var product: RvStoreProduct


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RvPackage? {
    let identifier = pigeonVar_list[0] as! String
    let packageType: RvPackageType? = nilOrValue(pigeonVar_list[1])
    let product = pigeonVar_list[2] as! RvStoreProduct

    return RvPackage(
      identifier: identifier,
      packageType: packageType,
      product: product
    )
  }
  func toList() -> [Any?] {
    return [
      identifier,
      packageType,
      product,
    ]
  }
}

/// Mirrors `OfferingDTO`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RvOffering {
  var identifier: String
  var isDefault: Bool
  var packages: [RvPackage]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RvOffering? {
    let identifier = pigeonVar_list[0] as! String
    let isDefault = pigeonVar_list[1] as! Bool
    let packages = pigeonVar_list[2] as! [RvPackage]

    return RvOffering(
      identifier: identifier,
      isDefault: isDefault,
      packages: packages
    )
  }
  func toList() -> [Any?] {
    return [
      identifier,
      isDefault,
      packages,
    ]
  }
}

/// Mirrors `OfferingsDTO`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RvOfferings {
  var current: String? = nil
  var offerings: [RvOffering]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RvOfferings? {
    let current: String? = nilOrValue(pigeonVar_list[0])
    let offerings = pigeonVar_list[1] as! [RvOffering]

    return RvOfferings(
      current: current,
      offerings: offerings
    )
  }
  func toList() -> [Any?] {
    return [
      current,
      offerings,
    ]
  }
}

/// Mirrors `PresentedContextDTO`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RvPresentedContext {
  var placementId: String
  var paywallId: String
  var variantId: String? = nil
  var experimentKey: String? = nil
  var revision: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RvPresentedContext? {
    let placementId = pigeonVar_list[0] as! String
    let paywallId = pigeonVar_list[1] as! String
    let variantId: String? = nilOrValue(pigeonVar_list[2])
    let experimentKey: String? = nilOrValue(pigeonVar_list[3])
    let revision = pigeonVar_list[4] as! Int64

    return RvPresentedContext(
      placementId: placementId,
      paywallId: paywallId,
      variantId: variantId,
      experimentKey: experimentKey,
      revision: revision
    )
  }
  func toList() -> [Any?] {
    return [
      placementId,
      paywallId,
      variantId,
      experimentKey,
      revision,
    ]
  }
}

/// Mirrors `PaywallDTO`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RvPaywall {
  var placementIdentifier: String
  var placementRevision: Int64
  var paywallIdentifier: String? = nil
  var paywallName: String? = nil
  var configFormatVersion: Int64
  var remoteConfigJson: String? = nil
  var remoteConfigLocale: String? = nil
  var builderConfigJson: String? = nil
  var offering: RvOffering? = nil
  var presentedContext: RvPresentedContext? = nil
  var servedFromFallback: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RvPaywall? {
    let placementIdentifier = pigeonVar_list[0] as! String
    let placementRevision = pigeonVar_list[1] as! Int64
    let paywallIdentifier: String? = nilOrValue(pigeonVar_list[2])
    let paywallName: String? = nilOrValue(pigeonVar_list[3])
    let configFormatVersion = pigeonVar_list[4] as! Int64
    let remoteConfigJson: String? = nilOrValue(pigeonVar_list[5])
    let remoteConfigLocale: String? = nilOrValue(pigeonVar_list[6])
    let builderConfigJson: String? = nilOrValue(pigeonVar_list[7])
    let offering: RvOffering? = nilOrValue(pigeonVar_list[8])
    let presentedContext: RvPresentedContext? = nilOrValue(pigeonVar_list[9])
    let servedFromFallback = pigeonVar_list[10] as! Bool

    return RvPaywall(
      placementIdentifier: placementIdentifier,
      placementRevision: placementRevision,
      paywallIdentifier: paywallIdentifier,
      paywallName: paywallName,
      configFormatVersion: configFormatVersion,
      remoteConfigJson: remoteConfigJson,
      remoteConfigLocale: remoteConfigLocale,
      builderConfigJson: builderConfigJson,
      offering: offering,
      presentedContext: presentedContext,
      servedFromFallback: servedFromFallback
    )
  }
  func toList() -> [Any?] {
    return [
      placementIdentifier,
      placementRevision,
      paywallIdentifier,
      paywallName,
      configFormatVersion,
      remoteConfigJson,
      remoteConfigLocale,
      builderConfigJson,
      offering,
      presentedContext,
      servedFromFallback,
    ]
  }
}

/// Mirrors `ExperimentAssignmentDTO`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RvExperimentAssignment {
  var experimentId: String
  var key: String
  var variantId: String
  var variantName: String
  var valueJson: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RvExperimentAssignment? {
    let experimentId = pigeonVar_list[0] as! String
    let key = pigeonVar_list[1] as! String
    let variantId = pigeonVar_list[2] as! String
    let variantName = pigeonVar_list[3] as! String
    let valueJson = pigeonVar_list[4] as! String

    return RvExperimentAssignment(
      experimentId: experimentId,
      key: key,
      variantId: variantId,
      variantName: variantName,
      valueJson: valueJson
    )
  }
  func toList() -> [Any?] {
    return [
      experimentId,
      key,
      variantId,
      variantName,
      valueJson,
    ]
  }
}

/// Mirrors `PurchaseResultDTO`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RvPurchaseResult {
  var entitlements: [RvEntitlement]
  var virtualCurrencies: [String: Int64]
  var productId: String
  var storeTransactionId: String
  var isDeferred: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RvPurchaseResult? {
    let entitlements = pigeonVar_list[0] as! [RvEntitlement]
    let virtualCurrencies = pigeonVar_list[1] as! [String: Int64]
    let productId = pigeonVar_list[2] as! String
    let storeTransactionId = pigeonVar_list[3] as! String
    let isDeferred = pigeonVar_list[4] as! Bool

    return RvPurchaseResult(
      entitlements: entitlements,
      virtualCurrencies: virtualCurrencies,
      productId: productId,
      storeTransactionId: storeTransactionId,
      isDeferred: isDeferred
    )
  }
  func toList() -> [Any?] {
    return [
      entitlements,
      virtualCurrencies,
      productId,
      storeTransactionId,
      isDeferred,
    ]
  }
}

/// Mirrors the `{ subscriberId, funnelAnswersJson }` shape returned by
/// `claimFunnelToken` / `claimInstall` / `claimFromClipboard` and emitted by
/// the `onFunnelClaimResolved` native event.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RvFunnelClaim {
  var subscriberId: String
  var funnelAnswersJson: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RvFunnelClaim? {
    let subscriberId = pigeonVar_list[0] as! String
    let funnelAnswersJson = pigeonVar_list[1] as! String

    return RvFunnelClaim(
      subscriberId: subscriberId,
      funnelAnswersJson: funnelAnswersJson
    )
  }
  func toList() -> [Any?] {
    return [
      subscriberId,
      funnelAnswersJson,
    ]
  }
}

/// Mirrors `claimInstall`'s `params` object — all fields optional.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RvClaimInstallParams {
  var platform: String? = nil
  var locale: String? = nil
  var timezone: String? = nil
  var screenDims: String? = nil
  var deviceModel: String? = nil
  var installReferrer: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RvClaimInstallParams? {
    let platform: String? = nilOrValue(pigeonVar_list[0])
    let locale: String? = nilOrValue(pigeonVar_list[1])
    let timezone: String? = nilOrValue(pigeonVar_list[2])
    let screenDims: String? = nilOrValue(pigeonVar_list[3])
    let deviceModel: String? = nilOrValue(pigeonVar_list[4])
    let installReferrer: String? = nilOrValue(pigeonVar_list[5])

    return RvClaimInstallParams(
      platform: platform,
      locale: locale,
      timezone: timezone,
      screenDims: screenDims,
      deviceModel: deviceModel,
      installReferrer: installReferrer
    )
  }
  func toList() -> [Any?] {
    return [
      platform,
      locale,
      timezone,
      screenDims,
      deviceModel,
      installReferrer,
    ]
  }
}

/// Mirrors the native `onChange` event payload (`{ event: ChangeEvent }`).
///
/// Generated class from Pigeon that represents data sent in messages.
struct RvChangeEvent {
  var kind: RvChangeEventKind


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RvChangeEvent? {
    let kind = pigeonVar_list[0] as! RvChangeEventKind

    return RvChangeEvent(
      kind: kind
    )
  }
  func toList() -> [Any?] {
    return [
      kind
    ]
  }
}

/// Mirrors `LogEntryDTO`.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RvLogRecord {
  var level: RvLogLevel
  var message: String
  var fields: [String: String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RvLogRecord? {
    let level = pigeonVar_list[0] as! RvLogLevel
    let message = pigeonVar_list[1] as! String
    let fields = pigeonVar_list[2] as! [String: String]

    return RvLogRecord(
      level: level,
      message: message,
      fields: fields
    )
  }
  func toList() -> [Any?] {
    return [
      level,
      message,
      fields,
    ]
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return RvLogLevel(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return RvProductType(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return RvSessionEventKind(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return RvProductCategory(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return RvPeriodUnit(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return RvPaymentMode(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return RvDiscountType(rawValue: enumResultAsInt)
      }
      return nil
    case 136:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return RvRecurrenceMode(rawValue: enumResultAsInt)
      }
      return nil
    case 137:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return RvPackageType(rawValue: enumResultAsInt)
      }
      return nil
    case 138:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return RvChangeEventKind(rawValue: enumResultAsInt)
      }
      return nil
    case 139:
      return RvUser.fromList(self.readValue() as! [Any?])
    case 140:
      return RvEntitlement.fromList(self.readValue() as! [Any?])
    case 141:
      return RvPeriod.fromList(self.readValue() as! [Any?])
    case 142:
      return RvIntroPrice.fromList(self.readValue() as! [Any?])
    case 143:
      return RvDiscount.fromList(self.readValue() as! [Any?])
    case 144:
      return RvPricingPhase.fromList(self.readValue() as! [Any?])
    case 145:
      return RvSubscriptionOption.fromList(self.readValue() as! [Any?])
    case 146:
      return RvStoreProduct.fromList(self.readValue() as! [Any?])
    case 147:
      return RvPackage.fromList(self.readValue() as! [Any?])
    case 148:
      return RvOffering.fromList(self.readValue() as! [Any?])
    case 149:
      return RvOfferings.fromList(self.readValue() as! [Any?])
    case 150:
      return RvPresentedContext.fromList(self.readValue() as! [Any?])
    case 151:
      return RvPaywall.fromList(self.readValue() as! [Any?])
    case 152:
      return RvExperimentAssignment.fromList(self.readValue() as! [Any?])
    case 153:
      return RvPurchaseResult.fromList(self.readValue() as! [Any?])
    case 154:
      return RvFunnelClaim.fromList(self.readValue() as! [Any?])
    case 155:
      return RvClaimInstallParams.fromList(self.readValue() as! [Any?])
    case 156:
      return RvChangeEvent.fromList(self.readValue() as! [Any?])
    case 157:
      return RvLogRecord.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? RvLogLevel {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? RvProductType {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? RvSessionEventKind {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? RvProductCategory {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? RvPeriodUnit {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? RvPaymentMode {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? RvDiscountType {
      super.writeByte(135)
      super.writeValue(value.rawValue)
    } else if let value = value as? RvRecurrenceMode {
      super.writeByte(136)
      super.writeValue(value.rawValue)
    } else if let value = value as? RvPackageType {
      super.writeByte(137)
      super.writeValue(value.rawValue)
    } else if let value = value as? RvChangeEventKind {
      super.writeByte(138)
      super.writeValue(value.rawValue)
    } else if let value = value as? RvUser {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? RvEntitlement {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? RvPeriod {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? RvIntroPrice {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? RvDiscount {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? RvPricingPhase {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? RvSubscriptionOption {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? RvStoreProduct {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? RvPackage {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? RvOffering {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else if let value = value as? RvOfferings {
      super.writeByte(149)
      super.writeValue(value.toList())
    } else if let value = value as? RvPresentedContext {
      super.writeByte(150)
      super.writeValue(value.toList())
    } else if let value = value as? RvPaywall {
      super.writeByte(151)
      super.writeValue(value.toList())
    } else if let value = value as? RvExperimentAssignment {
      super.writeByte(152)
      super.writeValue(value.toList())
    } else if let value = value as? RvPurchaseResult {
      super.writeByte(153)
      super.writeValue(value.toList())
    } else if let value = value as? RvFunnelClaim {
      super.writeByte(154)
      super.writeValue(value.toList())
    } else if let value = value as? RvClaimInstallParams {
      super.writeByte(155)
      super.writeValue(value.toList())
    } else if let value = value as? RvChangeEvent {
      super.writeByte(156)
      super.writeValue(value.toList())
    } else if let value = value as? RvLogRecord {
      super.writeByte(157)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol RovenueHostApi {
  func configure(apiKey: String, baseUrl: String?, logLevel: RvLogLevel, appVersion: String?, environment: String?) throws
  func shutdown() throws
  func setForeground(foreground: Bool) throws
  func getVersion() throws -> String
  func getAppVersion() throws -> String?
  func currentUser(completion: @escaping (Result<RvUser, Error>) -> Void)
  func identify(appUserId: String, completion: @escaping (Result<Void, Error>) -> Void)
  func logOut(completion: @escaping (Result<Void, Error>) -> Void)
  func entitlement(id: String, completion: @escaping (Result<RvEntitlement?, Error>) -> Void)
  func entitlementsAll(completion: @escaping (Result<[RvEntitlement], Error>) -> Void)
  func refreshEntitlements(completion: @escaping (Result<Void, Error>) -> Void)
  func virtualCurrencies(completion: @escaping (Result<[String: Int64], Error>) -> Void)
  func virtualCurrency(code: String, completion: @escaping (Result<Int64, Error>) -> Void)
  func refreshVirtualCurrencies(completion: @escaping (Result<Void, Error>) -> Void)
  func getOfferings(completion: @escaping (Result<RvOfferings, Error>) -> Void)
  func getPaywall(placementId: String, locale: String?, completion: @escaping (Result<RvPaywall?, Error>) -> Void)
  func setFallbackPlacements(json: String, completion: @escaping (Result<Int64, Error>) -> Void)
  func purchase(productId: String, productType: RvProductType, promotionalOfferId: String?, basePlanId: String?, offerId: String?, completion: @escaping (Result<RvPurchaseResult, Error>) -> Void)
  func restorePurchases(completion: @escaping (Result<RvPurchaseResult, Error>) -> Void)
  func refreshRemoteConfig(completion: @escaping (Result<Void, Error>) -> Void)
  func remoteConfigBool(key: String, fallback: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func remoteConfigString(key: String, fallback: String, completion: @escaping (Result<String, Error>) -> Void)
  func remoteConfigInt(key: String, fallback: Int64, completion: @escaping (Result<Int64, Error>) -> Void)
  func remoteConfigDouble(key: String, fallback: Double, completion: @escaping (Result<Double, Error>) -> Void)
  func remoteConfigJson(key: String, completion: @escaping (Result<String?, Error>) -> Void)
  func remoteConfigKeys(completion: @escaping (Result<[String], Error>) -> Void)
  func remoteConfigAllJson(completion: @escaping (Result<String, Error>) -> Void)
  func experiment(key: String, completion: @escaping (Result<RvExperimentAssignment?, Error>) -> Void)
  func experimentsAll(completion: @escaping (Result<[RvExperimentAssignment], Error>) -> Void)
  func getAppAccountToken(completion: @escaping (Result<String, Error>) -> Void)
  func recordSessionEvent(kind: RvSessionEventKind, occurredAt: String, durationMs: Int64?, completion: @escaping (Result<Void, Error>) -> Void)
  func flushSessionEvents(completion: @escaping (Result<Int64, Error>) -> Void)
  func claimFunnelToken(token: String, completion: @escaping (Result<RvFunnelClaim, Error>) -> Void)
  func claimInstall(params: RvClaimInstallParams, completion: @escaping (Result<RvFunnelClaim?, Error>) -> Void)
  func claimViaEmail(email: String, completion: @escaping (Result<Void, Error>) -> Void)
  func claimFromClipboard(completion: @escaping (Result<RvFunnelClaim?, Error>) -> Void)
  func installId(completion: @escaping (Result<String, Error>) -> Void)
  func hasResolvedFunnelClaim(completion: @escaping (Result<Bool, Error>) -> Void)
  func track(envelopeJson: String, completion: @escaping (Result<Void, Error>) -> Void)
  func enqueuePaywallEvent(envelopeJson: String, completion: @escaping (Result<Void, Error>) -> Void)
  func setAttributes(attributes: [String: String?], completion: @escaping (Result<Void, Error>) -> Void)
  func setEmail(email: String?, completion: @escaping (Result<Void, Error>) -> Void)
  func setDisplayName(name: String?, completion: @escaping (Result<Void, Error>) -> Void)
  func setPhoneNumber(phone: String?, completion: @escaping (Result<Void, Error>) -> Void)
  func setPushToken(token: String?, completion: @escaping (Result<Void, Error>) -> Void)
  func flushAttributes(completion: @escaping (Result<Int64, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class RovenueHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `RovenueHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: RovenueHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let configureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.configure\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let apiKeyArg = args[0] as! String
        let baseUrlArg: String? = nilOrValue(args[1])
        let logLevelArg = args[2] as! RvLogLevel
        let appVersionArg: String? = nilOrValue(args[3])
        let environmentArg: String? = nilOrValue(args[4])
        do {
          try api.configure(apiKey: apiKeyArg, baseUrl: baseUrlArg, logLevel: logLevelArg, appVersion: appVersionArg, environment: environmentArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      configureChannel.setMessageHandler(nil)
    }
    let shutdownChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.shutdown\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      shutdownChannel.setMessageHandler { _, reply in
        do {
          try api.shutdown()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      shutdownChannel.setMessageHandler(nil)
    }
    let setForegroundChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.setForeground\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setForegroundChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let foregroundArg = args[0] as! Bool
        do {
          try api.setForeground(foreground: foregroundArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setForegroundChannel.setMessageHandler(nil)
    }
    let getVersionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.getVersion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getVersionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getVersion()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getVersionChannel.setMessageHandler(nil)
    }
    let getAppVersionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.getAppVersion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAppVersionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getAppVersion()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAppVersionChannel.setMessageHandler(nil)
    }
    let currentUserChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.currentUser\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      currentUserChannel.setMessageHandler { _, reply in
        api.currentUser { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      currentUserChannel.setMessageHandler(nil)
    }
    let identifyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.identify\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      identifyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let appUserIdArg = args[0] as! String
        api.identify(appUserId: appUserIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      identifyChannel.setMessageHandler(nil)
    }
    let logOutChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.logOut\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      logOutChannel.setMessageHandler { _, reply in
        api.logOut { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      logOutChannel.setMessageHandler(nil)
    }
    let entitlementChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.entitlement\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      entitlementChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        api.entitlement(id: idArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      entitlementChannel.setMessageHandler(nil)
    }
    let entitlementsAllChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.entitlementsAll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      entitlementsAllChannel.setMessageHandler { _, reply in
        api.entitlementsAll { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      entitlementsAllChannel.setMessageHandler(nil)
    }
    let refreshEntitlementsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.refreshEntitlements\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      refreshEntitlementsChannel.setMessageHandler { _, reply in
        api.refreshEntitlements { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      refreshEntitlementsChannel.setMessageHandler(nil)
    }
    let virtualCurrenciesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.virtualCurrencies\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      virtualCurrenciesChannel.setMessageHandler { _, reply in
        api.virtualCurrencies { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      virtualCurrenciesChannel.setMessageHandler(nil)
    }
    let virtualCurrencyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.virtualCurrency\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      virtualCurrencyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let codeArg = args[0] as! String
        api.virtualCurrency(code: codeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      virtualCurrencyChannel.setMessageHandler(nil)
    }
    let refreshVirtualCurrenciesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.refreshVirtualCurrencies\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      refreshVirtualCurrenciesChannel.setMessageHandler { _, reply in
        api.refreshVirtualCurrencies { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      refreshVirtualCurrenciesChannel.setMessageHandler(nil)
    }
    let getOfferingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.getOfferings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getOfferingsChannel.setMessageHandler { _, reply in
        api.getOfferings { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getOfferingsChannel.setMessageHandler(nil)
    }
    let getPaywallChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.getPaywall\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPaywallChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let placementIdArg = args[0] as! String
        let localeArg: String? = nilOrValue(args[1])
        api.getPaywall(placementId: placementIdArg, locale: localeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getPaywallChannel.setMessageHandler(nil)
    }
    let setFallbackPlacementsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.setFallbackPlacements\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setFallbackPlacementsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let jsonArg = args[0] as! String
        api.setFallbackPlacements(json: jsonArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setFallbackPlacementsChannel.setMessageHandler(nil)
    }
    let purchaseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.purchase\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      purchaseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let productIdArg = args[0] as! String
        let productTypeArg = args[1] as! RvProductType
        let promotionalOfferIdArg: String? = nilOrValue(args[2])
        let basePlanIdArg: String? = nilOrValue(args[3])
        let offerIdArg: String? = nilOrValue(args[4])
        api.purchase(productId: productIdArg, productType: productTypeArg, promotionalOfferId: promotionalOfferIdArg, basePlanId: basePlanIdArg, offerId: offerIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      purchaseChannel.setMessageHandler(nil)
    }
    let restorePurchasesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.restorePurchases\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      restorePurchasesChannel.setMessageHandler { _, reply in
        api.restorePurchases { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      restorePurchasesChannel.setMessageHandler(nil)
    }
    let refreshRemoteConfigChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.refreshRemoteConfig\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      refreshRemoteConfigChannel.setMessageHandler { _, reply in
        api.refreshRemoteConfig { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      refreshRemoteConfigChannel.setMessageHandler(nil)
    }
    let remoteConfigBoolChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.remoteConfigBool\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      remoteConfigBoolChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let fallbackArg = args[1] as! Bool
        api.remoteConfigBool(key: keyArg, fallback: fallbackArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      remoteConfigBoolChannel.setMessageHandler(nil)
    }
    let remoteConfigStringChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.remoteConfigString\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      remoteConfigStringChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let fallbackArg = args[1] as! String
        api.remoteConfigString(key: keyArg, fallback: fallbackArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      remoteConfigStringChannel.setMessageHandler(nil)
    }
    let remoteConfigIntChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.remoteConfigInt\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      remoteConfigIntChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let fallbackArg = args[1] as! Int64
        api.remoteConfigInt(key: keyArg, fallback: fallbackArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      remoteConfigIntChannel.setMessageHandler(nil)
    }
    let remoteConfigDoubleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.remoteConfigDouble\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      remoteConfigDoubleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let fallbackArg = args[1] as! Double
        api.remoteConfigDouble(key: keyArg, fallback: fallbackArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      remoteConfigDoubleChannel.setMessageHandler(nil)
    }
    let remoteConfigJsonChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.remoteConfigJson\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      remoteConfigJsonChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        api.remoteConfigJson(key: keyArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      remoteConfigJsonChannel.setMessageHandler(nil)
    }
    let remoteConfigKeysChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.remoteConfigKeys\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      remoteConfigKeysChannel.setMessageHandler { _, reply in
        api.remoteConfigKeys { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      remoteConfigKeysChannel.setMessageHandler(nil)
    }
    let remoteConfigAllJsonChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.remoteConfigAllJson\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      remoteConfigAllJsonChannel.setMessageHandler { _, reply in
        api.remoteConfigAllJson { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      remoteConfigAllJsonChannel.setMessageHandler(nil)
    }
    let experimentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.experiment\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      experimentChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        api.experiment(key: keyArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      experimentChannel.setMessageHandler(nil)
    }
    let experimentsAllChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.experimentsAll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      experimentsAllChannel.setMessageHandler { _, reply in
        api.experimentsAll { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      experimentsAllChannel.setMessageHandler(nil)
    }
    let getAppAccountTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.getAppAccountToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAppAccountTokenChannel.setMessageHandler { _, reply in
        api.getAppAccountToken { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getAppAccountTokenChannel.setMessageHandler(nil)
    }
    let recordSessionEventChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.recordSessionEvent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      recordSessionEventChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let kindArg = args[0] as! RvSessionEventKind
        let occurredAtArg = args[1] as! String
        let durationMsArg: Int64? = nilOrValue(args[2])
        api.recordSessionEvent(kind: kindArg, occurredAt: occurredAtArg, durationMs: durationMsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      recordSessionEventChannel.setMessageHandler(nil)
    }
    let flushSessionEventsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.flushSessionEvents\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      flushSessionEventsChannel.setMessageHandler { _, reply in
        api.flushSessionEvents { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      flushSessionEventsChannel.setMessageHandler(nil)
    }
    let claimFunnelTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.claimFunnelToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      claimFunnelTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tokenArg = args[0] as! String
        api.claimFunnelToken(token: tokenArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      claimFunnelTokenChannel.setMessageHandler(nil)
    }
    let claimInstallChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.claimInstall\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      claimInstallChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let paramsArg = args[0] as! RvClaimInstallParams
        api.claimInstall(params: paramsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      claimInstallChannel.setMessageHandler(nil)
    }
    let claimViaEmailChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.claimViaEmail\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      claimViaEmailChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let emailArg = args[0] as! String
        api.claimViaEmail(email: emailArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      claimViaEmailChannel.setMessageHandler(nil)
    }
    let claimFromClipboardChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.claimFromClipboard\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      claimFromClipboardChannel.setMessageHandler { _, reply in
        api.claimFromClipboard { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      claimFromClipboardChannel.setMessageHandler(nil)
    }
    let installIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.installId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      installIdChannel.setMessageHandler { _, reply in
        api.installId { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      installIdChannel.setMessageHandler(nil)
    }
    let hasResolvedFunnelClaimChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.hasResolvedFunnelClaim\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      hasResolvedFunnelClaimChannel.setMessageHandler { _, reply in
        api.hasResolvedFunnelClaim { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      hasResolvedFunnelClaimChannel.setMessageHandler(nil)
    }
    let trackChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.track\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trackChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let envelopeJsonArg = args[0] as! String
        api.track(envelopeJson: envelopeJsonArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      trackChannel.setMessageHandler(nil)
    }
    let enqueuePaywallEventChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.enqueuePaywallEvent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      enqueuePaywallEventChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let envelopeJsonArg = args[0] as! String
        api.enqueuePaywallEvent(envelopeJson: envelopeJsonArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      enqueuePaywallEventChannel.setMessageHandler(nil)
    }
    let setAttributesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.setAttributes\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setAttributesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let attributesArg = args[0] as! [String: String?]
        api.setAttributes(attributes: attributesArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setAttributesChannel.setMessageHandler(nil)
    }
    let setEmailChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.setEmail\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setEmailChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let emailArg: String? = nilOrValue(args[0])
        api.setEmail(email: emailArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setEmailChannel.setMessageHandler(nil)
    }
    let setDisplayNameChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.setDisplayName\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setDisplayNameChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg: String? = nilOrValue(args[0])
        api.setDisplayName(name: nameArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setDisplayNameChannel.setMessageHandler(nil)
    }
    let setPhoneNumberChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.setPhoneNumber\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPhoneNumberChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let phoneArg: String? = nilOrValue(args[0])
        api.setPhoneNumber(phone: phoneArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setPhoneNumberChannel.setMessageHandler(nil)
    }
    let setPushTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.setPushToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPushTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tokenArg: String? = nilOrValue(args[0])
        api.setPushToken(token: tokenArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setPushTokenChannel.setMessageHandler(nil)
    }
    let flushAttributesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueHostApi.flushAttributes\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      flushAttributesChannel.setMessageHandler { _, reply in
        api.flushAttributes { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      flushAttributesChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol RovenueFlutterApiProtocol {
  func onChange(event eventArg: RvChangeEvent, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onLog(record recordArg: RvLogRecord, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onFunnelClaim(claim claimArg: RvFunnelClaim, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class RovenueFlutterApi: RovenueFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onChange(event eventArg: RvChangeEvent, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueFlutterApi.onChange\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onLog(record recordArg: RvLogRecord, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueFlutterApi.onLog\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([recordArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onFunnelClaim(claim claimArg: RvFunnelClaim, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.rovenue_flutter_platform_interface.RovenueFlutterApi.onFunnelClaim\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([claimArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
